spec/classes/foreman_cli_spec.rb
spec/classes/foreman_config_ipa_spec.rb
spec/classes/foreman_database_spec.rb
spec/classes/foreman_install_repos_extra_spec.rb

Work in Progress. Could be merged as it though.

Use rspec-puppet-facts

---

manifests/config/passenger.pp
manifests/params.pp
metadata.json
spec/classes/foreman_config_passenger_spec.rb
templates/_ssl_virt_host_include.erb
templates/_virt_host_include.erb

Untested at the moment, will continue soon and do the same for puppet-puppet.

Update to puppetlabs-apache 1.2.0

---

manifests/init.pp
manifests/params.pp
templates/database.yml.erb

add pool parameter

---

spec/classes/foreman_config_spec.rb

after theforeman/puppet-concat_native#11

fix concat paths in tests

---

lib/puppet/provider/foreman_smartproxy/rest_v2.rb

Opinions on warnings instead of errors? Since registration step is not fatal
and it often confuses users I'd vote for this. Otherwise I can just raise an
error with `raise "bla bla"`

Fixes #10466 - nice error on proxy registration error

---

.gitignore
manifests/config.pp
manifests/init.pp
manifests/params.pp
spec/classes/foreman_config_spec.rb
templates/email.yaml.erb

Added template, config, and params for managing content of the email.yaml file which configures email settings for theforeman.

Allow changing email settings for foreman through params

---

manifests/install/repos/extra.pp
spec/classes/foreman_install_repos_extra_spec.rb

Untested, will try to check it's all OK later.
http://projects.theforeman.org/issues/11069

fixes #11069 - add brightbox/passenger-legacy PPA for Passenger

---

manifests/rake.pp
manifests/service.pp
spec/classes/foreman_database_spec.rb
spec/classes/foreman_service_spec.rb
spec/defines/foreman_config_passenger_fragment_spec.rb
spec/defines/foreman_rake_spec.rb

This should save time on running tests

Do not include foreman as a pre condition

---

manifests/install/repos.pp

Resource names are not limited by scope.

Don't qualified call to defined resource type

---

manifests/config/passenger.pp
spec/classes/foreman_config_passenger_spec.rb

This PR exports the client certificate to the rails env, needed by http://projects.theforeman.org/issues/12127

add ExportCertData option needed by #12127

---

spec/classes/foreman_cli_spec.rb
spec/classes/foreman_config_ipa_spec.rb
spec/classes/foreman_config_passenger_spec.rb
spec/classes/foreman_config_spec.rb
spec/classes/foreman_database_spec.rb
spec/classes/foreman_install_repos_extra_spec.rb
spec/classes/foreman_install_spec.rb
spec/classes/foreman_plugin_discovery_spec.rb
spec/classes/foreman_plugin_openscap_spec.rb
spec/classes/foreman_plugin_ovirt_provision_spec.rb
spec/classes/foreman_plugin_puppetdb_spec.rb
spec/classes/foreman_plugin_remote_execution_spec.rb
spec/classes/foreman_plugin_tasks_spec.rb
spec/classes/foreman_puppetmaster_spec.rb
spec/classes/foreman_spec.rb
spec/defines/foreman_config_passenger_fragment_spec.rb
spec/defines/foreman_install_repos_apt_spec.rb
spec/defines/foreman_install_repos_spec.rb
spec/defines/foreman_plugin_spec.rb

This is pulled from https://github.com/theforeman/puppet-foreman/pull/332 and should be in a mergeable state.

Use rspec-puppet-facts where possible

---

spec/classes/foreman_plugin_discovery_spec.rb

I'm not sure why this is not working as expected, but it's a start...

fix discovery plugin specs

---

manifests/init.pp

updating RedHat to Red Hat on --help for EPEL repo

Fixes #14197 - Updating name on EPEL help

---

manifests/init.pp
manifests/params.pp
spec/classes/foreman_config_spec.rb
spec/classes/foreman_puppetmaster_spec.rb
spec/defines/foreman_repos_spec.rb
templates/settings.yaml.erb

see https://docs.puppetlabs.com/puppet/4.3/reference/whered_it_go.html#ssldir-is-inside-confdir

use different ssl dir on AIO

---

manifests/plugin.pp

Looking at this again, I merged that too early, this change should also go in.

correct 5c2f109

---

manifests/providers/params.pp
spec/classes/foreman_providers_spec.rb

this helps to get the correct package with non-AIO Puppet 4 packages.

improve AIO detection for oauth provider

---

manifests/config/passenger.pp
metadata.json
spec/classes/foreman_config_passenger_spec.rb
templates/_keepalive.erb

https://github.com/puppetlabs/puppetlabs-apache/commit/192d89427ade170a9c76fc0df0bcda0786c0cb53
added support for this so we can remove our custom fragment.

Use puppetlabs-apache keepalive options

---

CHANGELOG.md

Prepare 6.0.0 changelog

---

metadata.json

Permit theforeman/tftp module version 2.x

---

CHANGELOG.md

Prepare 7.0.0 changelog

---

manifests/config/passenger.pp

Allow overriding the apache log format

---

manifests/cli.pp
manifests/config.pp
manifests/database.pp
manifests/init.pp
manifests/plugin/puppetdb.pp
manifests/plugin/tasks.pp
manifests/repo.pp

To match style guide and for compatibility with puppet-lint 2.2.0.

Move chaining arrows to right operand line

---

lib/puppet/provider/foreman_smartproxy/rest_v3.rb
spec/unit/foreman_smartproxy_rest_v3_spec.rb

When refreshing the feature list on foreman_smartproxy via a notify,
validate it against the expected features to ensure they're all
configured correctly still.
The cached proxy data is replaced with the refresh response where
possible (since #19476) and is otherwise cleared to validate against
the new feature list (including via the `#features=` setter).

Validate feature list on foreman_smartproxy refresh

---

metadata.json

mark compatible with newer puppetlabs-postgresql

---

CHANGELOG.md

add changelog for 8.0.0

---

files/foreman-report_v2.rb
spec/unit/foreman_report_processor_spec.rb

This is GH-535 with a commit that adds tests.
Closes GH-534
Closes GH-535

Add retry to foreman reporting script

---

manifests/plugin/snapshot_management.pp
spec/classes/plugin/snapshot_management_spec.rb

This adds the already packaged plugin `foreman_snapshot_management`.
cc: @mdellweg

add plugin: foreman_snapshot_management

---

manifests/repos/apt.pp
spec/defines/foreman_repos_apt_spec.rb

Drop explicit source for pgp key

---

lib/puppet/parser/functions/foreman.rb

using theforeman as data source(without puppetdb). using ssl keys of foreman proxy for authentication.
require also change in foreman file ./app/controllers/api/v2/hosts_controller.rb
```
add_smart_proxy_filters :facts, :features => Proc.new { FactImporter.fact_features }
```
to
```
add_smart_proxy_filters [:facts,:index], :features => Proc.new { FactImporter.fact_features }
```

get data by ssl authentication

---

CHANGELOG.md

add 8.1.1 changelog

---

lib/puppet/functions/foreman/foreman.rb
lib/puppet/functions/foreman/smartvar.rb
spec/functions/foreman_foreman_spec.rb
spec/functions/foreman_smartvar_spec.rb

Use puppet4 functions-api

---

manifests/config.pp
spec/classes/foreman_config_ipa_spec.rb

Use selboolean for httpd_dbus_sssd

---

manifests/repos/yum.pp
spec/defines/foreman_repos_yum_spec.rb

This also tightens the defined type by using data types.

Handle releases/ properly for yum plugins repo

---

manifests/cli/discovery.pp
manifests/cli/openscap.pp
manifests/cli/plugin.pp
manifests/cli/remote_execution.pp
manifests/cli/tasks.pp
manifests/cli/templates.pp
spec/acceptance/foreman_cli_plugins_spec.rb
spec/classes/foreman_cli_discovery_spec.rb
spec/classes/foreman_cli_remote_execution_spec.rb
spec/classes/foreman_cli_tasks_spec.rb
spec/classes/foreman_cli_templates_spec.rb

This is not complete and there are more plugins, but this is a good start.

Add classes for hammer cli commands

---

manifests/cli/virt_who_configure.pp
manifests/plugin/virt_who_configure.pp
spec/classes/foreman_cli_virt_who_configure_spec.rb
spec/classes/plugin/virt_who_configure_spec.rb

This allows installing the core plugin and the hammer plugin.

Add support for foreman_virt_who_configure

---

manifests/plugin/spacewalk.pp
spec/classes/plugin/spacewalk_spec.rb

Adding spacewalk plugin.  RPM available [here](https://yum.theforeman.org/plugins/nightly/el7/x86_64/)

Adding spacewalk plugin

---

manifests/plugin/dlm.pp
spec/classes/plugin/dlm_spec.rb

Adding dlm plugin.  RPM available [here](https://yum.theforeman.org/plugins/nightly/el7/x86_64/)

Adding dlm plugin

---

manifests/config/passenger.pp

fix foreman config location for ssl = false and use_vhost = false

---

files/external_node_v2.rb
spec/unit/foreman_external_node_spec.rb

Fixup yaml facts prior to parsing in node.rb

---

manifests/config.pp
manifests/config/apache.pp
manifests/config/apache/fragment.pp
manifests/config/passenger/fragment.pp
spec/classes/foreman_config_apache_spec.rb
spec/classes/foreman_config_ipa_spec.rb
spec/classes/foreman_spec.rb
spec/defines/foreman_config_apache_fragment_spec.rb
spec/defines/foreman_config_passenger_fragment_spec.rb

Also uses some functions from stdlib to clean up code.

Refactor f::config::passenger to f::config::apache

---

manifests/plugin/cockpit.pp
spec/classes/plugin/cockpit_spec.rb

According to https://community.theforeman.org/t/sunsetting-foreman-cockpit/14787

Sunsetting foreman_cockpit because functionality being integrated in remote execution

---

manifests/plugin/azure.pp
spec/classes/plugin/azure_spec.rb

In reference with [foreman-installer/405](https://github.com/theforeman/foreman-installer/pull/405).

Initial AzureRM support

---

spec/acceptance/foreman_prometheus_spec.rb

This reverts commit c0b961134552c01efe58d44b4a0839d48fe2b2ed.

Revert "Skip the prometheus acceptance test on Debian"

---

metadata.json

Various changes have gone in that make this a new major version.

Bump version to 15.0.0

---

spec/acceptance/foreman_basic_spec.rb
spec/acceptance/foreman_cli_plugins_spec.rb
spec/acceptance/foreman_cli_spec.rb
spec/acceptance/foreman_journald_spec.rb
spec/acceptance/foreman_prometheus_spec.rb
spec/acceptance/foreman_rex_cockpit_spec.rb
spec/acceptance/foreman_statsd_spec.rb
spec/support/acceptance/purge.rb

This also fixes some small things.
It's the mergeable part of https://github.com/theforeman/puppet-foreman/pull/699.

Acceptance: Move cleanup to a helper method

---

Gemfile
manifests/params.pp
manifests/repos/yum.pp
metadata.json
spec/acceptance/foreman_basic_spec.rb
spec/acceptance/foreman_cli_plugins_spec.rb
spec/acceptance/foreman_cli_spec.rb
spec/acceptance/foreman_journald_spec.rb
spec/acceptance/foreman_prometheus_spec.rb
spec/acceptance/foreman_reverse_proxy_spec.rb
spec/acceptance/foreman_rex_cockpit_spec.rb
spec/acceptance/foreman_statsd_spec.rb
spec/defines/foreman_repos_yum_spec.rb
spec/setup_acceptance_node.pp
spec/spec_helper_acceptance.rb

This fixes repository handling for 2.0 and beyond. To test this easily, some acceptance tests are also cherry picked. It also marks it compatible with extlib 5.0.

14.0.1 cherry picks

---

lib/facter/sssd.rb
manifests/config.pp
spec/classes/foreman_config_ipa_spec.rb
templates/auth_kerb.conf.erb

This prevents a collision with the ipa fact from the ipa module.

Prefix ipa and sssd facts with foreman_

---

manifests/database.pp
manifests/init.pp
manifests/plugin.pp
spec/classes/foreman_database_spec.rb
spec/classes/foreman_spec.rb

@ekohl, please, let me know if I should link it to the Redmine or add/change something else.
My intention here is to add generating of DSL docs similarly to API docs after Foreman or a plugin is installed.

Fixes #31215 - Generate DSL docs

---

.github/workflows/acceptance.yml
.github/workflows/cron.yml
.sync.yml
Gemfile
spec/defines/foreman_repos_spec.rb

729b54c1355851da7ecacfca7b32d361a83fc03b missed a few parts.

Complete Github actions migration

---

README.md
manifests/config/apache.pp
manifests/init.pp
manifests/params.pp
spec/classes/foreman_config_apache_spec.rb
spec/classes/foreman_spec.rb

Changes include https://projects.theforeman.org/issues/29938 and a followup to https://projects.theforeman.org/issues/30535 fixing a typo

Cherry-picks for foreman 2.2.1

---

manifests/plugin/puppet.pp
spec/classes/plugin/puppet_spec.rb

Add foreman_puppet plugin

---

Gemfile
spec/acceptance/dynflow_spec.rb
spec/acceptance/foreman_basic_spec.rb
spec/acceptance/foreman_cli_plugins_spec.rb
spec/acceptance/foreman_cli_spec.rb
spec/acceptance/foreman_journald_spec.rb
spec/acceptance/foreman_prometheus_spec.rb
spec/acceptance/foreman_rex_cockpit_spec.rb
spec/acceptance/foreman_statsd_spec.rb
spec/spec_helper_acceptance.rb

Finally there's a released version of beaker-hiera that includes the fixes needed. voxpupuli-acceptance now includes this integration as well as some other changes we had locally. This leads to a smaller helper.

Switch to voxpupuli-acceptance 1.0

---

metadata.json

The breaking changes do not affect this module.

Allow puppet/redis 7.x

---

metadata.json

Needs:
* https://github.com/theforeman/puppet-katello/pull/422
* https://github.com/theforeman/puppet-foreman_proxy/pull/684

Bump version to 18.0.0

---

CHANGELOG.md

Potential open PRs for inclusion:
~~- [ ] https://github.com/theforeman/puppet-foreman/pull/960~~

Release 18.0.0

---

CHANGELOG.md
metadata.json

I'd like https://github.com/theforeman/puppet-foreman/pull/1016 to get in, though strictly not needed.

Release 19.2.0

---

manifests/plugin/google.pp
spec/classes/plugin/google_spec.rb

For [Foreman Installer - Foreman Google](https://github.com/theforeman/foreman-installer/pull/758)

Add Foreman Google plugin

---

manifests/database.pp
manifests/init.pp
manifests/plugin.pp
spec/classes/foreman_database_spec.rb
spec/classes/foreman_spec.rb

Depends on the outcome of https://github.com/theforeman/foreman/pull/9236

Fixes #34977: Drop apipie_dsl:cache generation

---

.sync.yml
lib/puppet/provider/foreman_global_parameter/rest_v3.rb
lib/puppet/provider/foreman_resource/rest_v3.rb
lib/puppet/type/foreman_global_parameter.rb
spec/acceptance/foreman_global_parameter_spec.rb
spec/spec_helper.rb
spec/unit/foreman_resource_rest_v3_spec.rb
spec/unit/provider/foreman_global_parameter/rest_v3_spec.rb
spec/unit/type/foreman_global_parameter_spec.rb

Master already has a breaking change, this branch and cherry picks is intended for a feature release for 20.X as requested in https://github.com/theforeman/puppet-foreman/pull/1061#issuecomment-1149605604

Cherry picks for a 20.2 release

---

manifests/plugin/netbox.pp
spec/classes/plugin/netbox_spec.rb

Depends on https://github.com/theforeman/foreman-packaging/pull/8021

Add foreman plugin for netbox

---

templates/auth_gssapi.conf.erb
templates/lookup_identity.conf.erb
templates/settings-external-auth.yaml.erb

Required by https://github.com/theforeman/foreman/pull/9406

Refs #35473 - Configure Apache for API extlogin

---

manifests/cli/google.pp
spec/acceptance/foreman_cli_plugins_spec.rb
spec/classes/cli_plugins_spec.rb

Refs #35675 - Add hammer-cli-foreman-google plugin

---

files/_assets.conf.erb

Fixes: 6a02be6e8faecb4210f16a8a5aea37397bfe3f74

Fixes #36028 - ensure compressed assets are returned if available

---

metadata.json

Update metadata to 23.1.0

---

manifests/plugin/hdm.pp
spec/classes/plugin/hdm_spec.rb

This PR adds the Foreman HDM plugin.

Add hiera data manager (HDM) plugin

---

manifests/config.pp
manifests/init.pp

Opening as a draft until I can test this properly.
Replaces #1100

Fixes #35832 - set default_domain_suffix in sssd.conf

---

Gemfile

For reference: https://github.com/theforeman/foreman-installer-modulesync/pull/155#pullrequestreview-2101938468

Update puppet_metadata to ~> 4.0 and voxpupuli-acceptance to ~> 3.0

---

manifests/plugin/rh_cloud.pp

needs https://github.com/theforeman/puppet-iop_advisor_engine/pull/14

pass the correct foreman url to iop advisor engine

---

manifests/cli/resource_quota.pp
spec/acceptance/foreman_cli_plugins_spec.rb
spec/classes/cli_plugins_spec.rb

This PR aims on adding hammer cli for the `foreman_resource_quota` plugin:
https://github.com/ATIX-AG/hammer-cli-foreman-resource-quota
It relates to this foreman-installer PR: https://github.com/theforeman/foreman-installer/pull/1007

Add hammer-cli-foreman-resource-quota package

---

manifests/config.pp

Similar to https://github.com/theforeman/puppet-foreman_proxy/commit/69d55c912d4d62eff43792d0413b088f4579d647

Fix linting error
