metadata.json

It was unreleased at the time of b5d8e4f, now it's 0.3.0.

Fix minimum alternatives version for dpkg/mode fix

---

manifests/plugin/discovery.pp
manifests/remote_file.pp

This fix is required to migration to the future parser.

Leading zeros need to be quoted

---

manifests/params.pp
manifests/puppetmaster.pp
spec/classes/foreman_puppetmaster_spec.rb
templates/puppet.yaml.erb

Make the node.rb timeout configurable. This is useful for use cases when
catalog compilation takes more time and/or the node.rb request to
Foreman is being handled by a freshly spawned Passenger worker.

Fixes #9286 - node.rb timeout too low and not configurable

---

manifests/install/repos/apt.pp

First pull request, let me know if I am doing anything wrong.
On my first puppet runs, I do not have internet access, and I discovered that the resource ordering in the apt repo installation causes later runs to fail as the theforeman deb sources never gets changed (which succeeds offline).

Initial puppet runs with no internet access cause failures on later runs

---

manifests/config/passenger.pp
manifests/params.pp
manifests/puppetmaster.pp
metadata.json

where possible, so there's still one occurence in ```manifests/install/repos/apt.pp```.
Support for Debian/squeeze was dropped for Foreman 1.7, so desupport it here as well.

fixes #9449 - drop usage of lsb facts

---

manifests/config/passenger.pp
spec/classes/foreman_config_passenger_spec.rb

When this class is used from kafo we don't have a way to disable CRL
configuration, since the parameter is String. It can't be set to false
and it's always present.

Make CRL optional in use with kafo

---

manifests/puppetmaster.pp

Depends on https://github.com/theforeman/puppet-puppet/issues/248
foreman::puppetmaster should be usable without our 'puppet' module.  Instead
for theforeman/puppet users, puppet::server::config is being updated to
correctly anchor the foreman::puppetmaster class.
Closes GH-129
---
I tested the two together just now, changed /etc/puppet/node.rb, re-ran the installer and it correctly refreshed the puppet master service, so the notification part of anchoring is working correctly.

Remove ordering constraints around theforeman/puppet

---

lib/puppet/provider/foreman_config_entry/cli.rb

The 'dry' method just returns :absent so always appears to be trueish, when it
should have been checking the dry parameter on the user's resource.

Fix foreman_config_entry checking of dry

---

.fixtures.yml
manifests/database/mysql.pp
spec/classes/foreman_config_spec.rb
spec/classes/foreman_database_spec.rb

Fix support for mysql by removing inclusion of mysql class which was removed by puppetlabs/mysql in version 3.0.0
Resolves issue #308

Do not include mysql class

---

lib/puppet/provider/foreman_config_entry/cli.rb

http://projects.theforeman.org/issues/9928
I haven't figured out why our nightly tests don't hit it, but our 1.8 tests did and I can reproduce it on both a nightly and 1.8 installation on 14.04.  You should see a `foreman-installer -v` tries to re-migrate/seed, or `puppet resource foreman_config_entry --modulepath /usr/share/foreman-installer/modules` simply fails with an error about collect.
The HOME var, like on the < 3.4 code path needed setting for rb-readline as foreman-config loads it and fails quietly otherwise.

fixes #9928 - set HOME for foreman-config on all Puppet versions

---

manifests/plugin/openscap.pp

Because the main class doesn't inherit the params class, the variable configure_openscap_repo is not set correctly.

fix configure_openscap_repo variable value

---

lib/puppet/provider/foreman_config_entry/cli.rb

foreman-config is deprecated and also not working for me on Debian/jessie, so change this to foreman-rake, which should be 100% compatible.

use foreman-rake instead of foreman-config

---

lib/puppet/provider/foreman_config_entry/cli.rb

(cherry picked from commit da98ce43634af1e4440c726804ba3b5357e97099)
I'd like to have this also in 3.0 and a 3.0.2 tagged and released, so 1.8 packages for Debian/jessie are possible.

use foreman-rake instead of foreman-config (also in 3.0)

---

manifests/init.pp
manifests/params.pp
spec/classes/foreman_config_spec.rb
templates/settings.yaml.erb

1. I took a shortcut with the `loggers` parameter in making it a one-level deep hash so you can only specify whether it's enabled or not, no other fancy options (overriding what's in logging.yaml).  This makes it usable from kafo (e.g. `foreman-installer --foreman-logging-level=debug --foreman-loggers=ldap:true`)
2. I didn't think templating logging.yaml was necessary, the main switches are in settings.yaml (see http://projects.theforeman.org/projects/foreman/wiki/Troubleshooting#How-do-I-enable-debugging).
3. The behaviour of `loggers` depends on ~~https://github.com/theforeman/foreman/pull/2437~~ which makes Foreman merge settings into sane defaults rather than us having to list all loggers here.  Best to wait for that PR before merging this.

fixes #5838 - add logging_level, loggers parameters

---

manifests/init.pp
manifests/install.pp
manifests/install/repos/extra.pp

The --foreman-configure-ipa-repo option is no longer required since the packages are included in RHEL/CentOS versions 6 and 7 now.
This feature was needed in older RHEL/CentOS versions, in which some packages weren't available. Now there is no need for it. We wanted to remove it from the documentation first and then from the code, after the comment from theforeman.org and discussion with @ares we decided to change it to deprecated and notify the user if he wants to use it.

The --foreman-configure-ipa-repo option is no longer required

---

manifests/puppetmaster.pp

This matches the puppet default and it reduces differences if you set a
global default in site.pp.

Set explicit permissions

---

manifests/init.pp
manifests/service.pp

Don't use a `case` instead of an `if`.
If there is a good reason for the `case` could we at least replace `default, false: {` with `default: {` ?

Cosmetic update in service.pp

---

manifests/init.pp

RDoc fails to parse lists when only tabs are present after the
parameter name.
---
Only the parameters with spaces after them were being found:
<pre>
found ["$plugin_prefix"]
found ["$logging_level"]
found ["$loggers"]
found ["$email_smtp_user_name"]
found ["$email_smtp_password"]
[FATAL 2015-09-02 07:32:54 fatal] Unable to continue because of: undocumented parameters in foreman: admin_email, admin_first_name, admin_last_name, admin_password, admin_username, apipie_task, app_root, authentication, configure_brightbox_repo, configure_epel_repo, configure_ipa_repo, configure_scl_repo, custom_repo, db_adapter, db_database, db_host, db_manage, db_password, db_pool, db_port, db_sslmode, db_type, db_username, email_conf, email_delivery_method, email_smtp_address, email_smtp_authentication, …

Change tabs to spaces in parameter documentation

---

files/external_node_v2.rb

Upload facts can timeout before the specified script timeout, which causes the script to exit 1. Since we have an overall timeout, just use that as the timeout setting for the http request.

Use the timeout setting in the http request

---

manifests/params.pp

CRL under ssl/ca/ca_crl.pem should only be available on a Puppet CA.
So when Foreman is running on any other host, the Apache config is not
working.

Prefer agent location of SSL CRL by default

---

.sync.yml
Gemfile

Scheduled to be released in 2.4.0:
https://github.com/sporkmonger/addressable/blob/master/CHANGELOG.md#addressable-240
Pre-emptive PR, as I happened to notice the deprecation warning.  It only affects puppet-foreman, since it's only a dependency of webmock.

Pin addressable to pre-2.4 for Ruby 1.8 support

---

spec/classes/foreman_plugin_discovery_spec.rb

The current test doesn't actually run because of `if facts[:os] == 'Fedora'`, I've included the refactored test from theforeman/puppet-foreman_proxy#203 that resolves the bug and improves the clarity.

fix + refactor foreman::plugin::discovery test

---

manifests/params.pp

Lower case FQDN used in the Foreman URL for apipie-bindings (in Hammer)
to work correctly and also to match foreman_proxy to ensure correct
ordering of foreman_smartproxy resources in init.pp's resource
collector.
---
Fixes the issue I noted in https://github.com/theforeman/puppet-foreman_proxy/pull/148#issuecomment-158368123, simply due to case sensitive comparisons in the init.pp resource collector.

refs #8389 - lower case Foreman hostname to match foreman_proxy

---

manifests/params.pp
spec/classes/foreman_config_spec.rb

Using the foreman-ruby symlink installed by our packages by default on
all Debian-based OSes will make upgrades easier, as users won't need to
reconfigure Apache if we change the Ruby version used by the packages.

Configure Passenger to use foreman-ruby symlink

---

lib/puppet/provider/foreman_config_entry/cli.rb

found while testing #383, where the value is an URL, containing a colon

fix key-value splitting in foreman_config_entry

---

CHANGELOG.md
manifests/init.pp
manifests/params.pp
spec/classes/foreman_config_spec.rb
templates/settings.yaml.erb

Added the param "puppetrun" to the foreman settings.yaml template (and params+init manifests) to toggle the puppetrun functionality in foreman. This enables the "Run Puppet" button on individual host pages. default value is false, since that was the default before.

added the param  puppetrun

---

manifests/puppetmaster.pp
spec/classes/foreman_puppetmaster_spec.rb

This commit changes the installation of rubygem-json from an explicit
package definition to ensure_packages. This may prevent a duplicate
declaration of the package resource.

ensure json_package is installed via ensure_packages

---

Gemfile

closes GH-396
will open a PR for modulesync, once this is merged here.

pin rspec-puppet-facts for Ruby 1.8

---

Gemfile
Rakefile
spec/spec_helper.rb

Unsure if we need that and it's still broken for Puppet 2.7, but I think this is better than before.

cherry-pick test fixes to 5.0-stable

---

manifests/config/passenger.pp
manifests/init.pp
manifests/params.pp
spec/classes/foreman_config_passenger_spec.rb
spec/defines/foreman_config_passenger_fragment_spec.rb
templates/_keepalive.erb

As it seems to be still a longer time to puppetlabs-apache 2.0, handle this in the vhost.
@lzap for your testing pleasure... :snail:

fixes #8489 - set KeepAlive On in foreman vhost

---

files/external_node_v2.rb

This fact allow to determine which puppet master is used by agent when using use_srv_records and srv_domain puppet settings. Furthermore it allow analize proxy load by adding this fact to trend counters.

add 'puppetmaster' fact value

---

manifests/init.pp
spec/classes/foreman_spec.rb

1b552f0 seems to have triggered this condition in our nightly tests, where adding both foreman and foreman::cli classes causes the foreman-cli package to be installed before repos are configured.
I don't think any dependency has ever been present, and it's because foreman-cli now depends on SCL packages on EL OSes that it's especially relevant now.

Order foreman::cli after repo setup

---

spec/functions/ensure_value_in_string_spec.rb
spec/functions/foreman_spec.rb
spec/functions/smartvar_spec.rb

Specs are rewritten to use the documented function testing helpers,
which fixes the errors seen under Puppet 4 with 2.4.0 due to changes
in initialisation.
Puppet::DevError:
Function ensure_value_in_string not defined despite being loaded!

Fix function spec failures under rspec-puppet 2.4.0

---

README.md
lib/puppet/provider/foreman_smartproxy/rest.rb
manifests/init.pp
manifests/providers.pp
manifests/providers/params.pp
spec/classes/foreman_providers_spec.rb
spec/classes/foreman_spec.rb

This will replace the package resource in foreman_proxy and help when
using the providers here outside of foreman_proxy.

Add foreman::providers to install provider dependencies

---

manifests/init.pp
manifests/params.pp
manifests/plugin.pp
spec/defines/foreman_plugin_spec.rb

This will allow the plugins to be kept updated.
In case that foreman is set to a fixed version, the version of plugins will need to be set also for all plugins.

allow plugins to be updated

---

manifests/init.pp

Allows the class to be included with class parameters from
puppet-foreman_proxy.

Change foreman::repo inclusion to 'include' keyword

---

manifests/providers.pp
spec/classes/foreman_providers_spec.rb

Prevents duplicate resources between foreman::providers and
foreman::puppetmaster on ruby/rubygem-json.

Change foreman::providers package resources to ensure_package()

---

manifests/params.pp
spec/classes/foreman_install_spec.rb

Foreman 1.12 requires it for access to the CentOS SCLo repositories
containing sclo-ror42.

Enable foreman-release-scl on RHEL

---

lib/puppet/provider/foreman_resource/rest_v3.rb
spec/unit/foreman_resource_rest_v3_spec.rb

Previously, the "data" param was passed to all oauth requests. This caused
issues with `GET` requests, since `data` and `headers` gets mashed into
`*arguments`, and then the oauth gem will `shift` off the first argument if
there's a `POST` or `PUT` method. The end result was that headers weren't being
sent on `GET` requests.
Instead, only supply the "data" param if we are doing a `POST` or `PUT`.

Fixes #14852 - do not pass in "data" param unless needed

---

lib/puppet/provider/foreman_resource/rest_v3.rb
spec/unit/foreman_resource_rest_v3_spec.rb

Fixes refreshing of smart proxies against Foreman, since the PUT
request data defaulted to `{}`. This causes the oauth gem to form
encode the empty hash data, overriding the Content-Type to application/
x-www-form-urlencoded and the request is rejected by Foreman with a 415
HTTP response.
https://github.com/oauth-xx/oauth-ruby/blob/v0.5.1/lib/oauth/consumer.rb#L362-L364 checks for a Hash overrides the content type.

Revert default rest_v3 request data to nil

---

manifests/init.pp
spec/classes/foreman_config_spec.rb
templates/settings.yaml.erb

These values are by foreman to communicate with its smart proxies.
Closes GH-441

Expose client_ssl_* config values

---

files/foreman-report_v2.rb
manifests/params.pp
manifests/puppetmaster.pp
spec/classes/foreman_puppetmaster_spec.rb
templates/puppet.yaml.erb

I have run into cases where a catalog and subsequent reports are so large that the default 60 second timeout in Net::HTTP is too short.  The reports are still uploaded but errors are thrown in puppetserver.

Support timeout configuration in foreman report processor

---

.fixtures.yml

restrict extlib version to be Ruby 1.8 compatible

---

spec/classes/foreman_config_passenger_spec.rb
templates/_ssl_virt_host_include.erb
templates/_virt_host_include.erb

The change with GH-418 missed to change 2 vhost fragment templates. The problem only got noticed by apache.
In addition I include spec tests to check for a proper usage of the conf.d directories.
(( We should include this in 5.2-stable branch with the next bugfix release ))

Fix a missing usage of the priority parameter in fragments

---

manifests/cli.pp

Puppet 3.7.4 and below are not able to check whether a variable is
defined in another class due to bug PUP-4072, so foreman::foreman_url
isn't used as defined() is returning false on these versions.
This change skips the defined() check for these versions to ensure it
always picks the URL from foreman::foreman_url, at the expense of not
supporting strict variables before Puppet 3.7.5.
---
Should fix issues found in Debian Jessie tests (http://ci.theforeman.org/job/release_nightly_test_deb/796/) where Hammer's foreman.yml had an empty `:host` value. It would also affect EPEL7's 3.6.2.
This can be tested if you like by setting `STRICT_VARIABLES` to yes/no on the various versions and running foreman_cli_spec.rb.

Skip defined() check for Foreman URL in CLI class on Puppet 3.6/7

---

manifests/database.pp
manifests/init.pp
manifests/params.pp
spec/classes/foreman_database_spec.rb
spec/classes/foreman_spec.rb

This makes it possible to have the databases on an external server,
using db_manage=false, while still populating the database with the
required rake jobs.
closes GH-473

introduce db_managed_rake flag

---

.fixtures.yml
.travis.yml

newer versions are not compatible with Ruby 1.8.7

pin puppetlabs-mysql to 3.9.0 for tests (6.0-stable)

---

manifests/params.pp
manifests/providers/params.pp

I'm working on adding Archlinux to puppet-foreman_proxy, and the tests need to load some package names from here. The packages exist (https://aur.archlinux.org/packages/?O=0&SeB=nd&K=apipie+or+ruby-json+or+ruby-oauth&outdated=&SB=n&SO=a&PP=50&do_Search=Go)
Archlinux isn't currently in the metadata.json, so I've not touched the tests.

Add Archlinux packages to provider::params

---

manifests/config/passenger.pp
manifests/service.pp
spec/classes/foreman_config_passenger_spec.rb
spec/classes/foreman_service_spec.rb
spec/classes/foreman_spec.rb

Two parts:
1. Move containment of Class['apache'] and Service['httpd'] so the service is contained within foreman::service, and the entire apache class is run at any time before the end of foreman::service (some of the config will be part of foreman::config::passenger etc).
1. Add dep to foreman::service on puppet::server::config ([mirror](https://github.com/theforeman/puppet-puppet/issues/453)).

fixes #17133 - add puppet::server::config (CA) dep to foreman::service

---

files/external_node_v2.rb

form source  $puppetdir/yaml/node/server.example.com
Usefull if we just want to send fact with --push-facts option.
Otherwise the environment is the default production on foreman

get environment fact value from puppet node file 

---

manifests/init.pp
spec/classes/foreman_spec.rb

When `db_manage` and `db_manage_rake` are both set to `false`,
there are no resources in `Class['foreman::database']` that get
refreshed when configuration changes. As a result,
`Class['foreman::service']` doesn't get notified and foreman isn't
restarted.
This commit adds an explicit relationship between
`Class['foreman::config']` and `Class['foreman::service']`.
Fixes #GH-502

Fix changes to config not restarting service

---

manifests/cli.pp
manifests/compute/ec2.pp
manifests/compute/foreman_compute.pp
manifests/compute/gce.pp
manifests/compute/libvirt.pp
manifests/compute/openstack.pp
manifests/compute/ovirt.pp
manifests/compute/rackspace.pp
manifests/compute/vmware.pp
manifests/init.pp
manifests/params.pp
manifests/plugin/discovery.pp
manifests/plugin/memcache.pp
manifests/plugin/ovirt_provision.pp
manifests/plugin/puppetdb.pp
manifests/plugin/tasks.pp

Supported since Kafo 1.0.0, it performs more precise validation of
parameter values and can later be moved to the parameter definitions
when the module is made Puppet 4-only.

Change existing Kafo type definitions to Puppet 4 types

---

manifests/config.pp
manifests/init.pp
manifests/params.pp
manifests/settings.pp
spec/classes/foreman_config_spec.rb
spec/classes/foreman_settings_spec.rb
spec/classes/foreman_spec.rb

Foreman 1.14+ stores email settings in its database when email.yaml
is absent. This can be configured by setting `email_config_method`
to 'database', defaulting to the file method for 1.13 compatibility.
---
Support in Foreman not quite merged, but likely to be shortly (http://projects.theforeman.org/issues/12156).
I'll also change the default value to `database` in foreman-installer's develop branch.

Support configuring email settings via foreman_config_entry

---

manifests/compute/ec2.pp
manifests/compute/foreman_compute.pp
manifests/compute/gce.pp
manifests/compute/libvirt.pp
manifests/compute/openstack.pp
manifests/compute/ovirt.pp
manifests/compute/rackspace.pp
manifests/compute/vmware.pp

When set to undef, the default "installed" value will be used anyway.
This works around Kafo issue [#6158](http://projects.theforeman.org/issues/6158) where string defaults on parameters
are ignored and stored as undef/nil.
---
Should fix failures seen in nightly tests using these compute classes, where Kafo's validation of `nil` against `String` raises errors:
<pre>
</pre>

Allow undef for foreman::compute::*::version parameters

---

manifests/init.pp

The code that configures it allows for blank string: https://github.com/theforeman/puppet-foreman/blob/master/manifests/config/passenger.pp#L172

Allow CRL to be blank string

---

manifests/config/passenger.pp

The issue that this workaround was designed to mitigate was corrected in
https://github.com/puppetlabs/puppetlabs-apache/commit/dfaae9a00cb70bb536bdd889ac3c4011f36e0c61
Reworked #511. Changing the base pulled in some other commits, it was easier to just reissue a new PR.

Disable docroot management properly.

---

manifests/init.pp

Kafo will already do that for us, and having defaults also in the docstring renders the output duplicated:
--foreman-manage-user         Controls whether foreman module will manage the user on the system. (default true) (default: true)

don't provide defaults in the docstrings of parameters

---

manifests/plugin/puppetdb.pp
manifests/plugin/puppetdb/params.pp

It is related to this
https://github.com/theforeman/puppetdb_foreman/commit/57f782c5502b4bdc7afcd56436bb303e182ddb45
Recently, I modified codes on the Puppetdb plugin for supporting PuppetDB 4.x.
But the foreman-installer does not reflect these changes.
I added few params on the puppetdb.pp file. these are all related to the client SSL certificate.
Please apply this request.

Puppetdb4 support

---

templates/_assets.conf.erb

With compression-webpack-plugin, precompressed files are also available
in `~foreman/public/webpack/` and may be served if available.

Extend gzip file serving to /public/webpack

---

manifests/plugin/discovery.pp
spec/classes/plugin/discovery_spec.rb

The problem is that puppet-foreman_proxy can define this directory, but that's not guaranteed since the user may not enable that plugin. In that case this dependency can't be satified which results in an error, at least on puppet 4.
The installer will give the following traceback:
```
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/errors.rb:106:in `fail'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1499:in `block in validate_relationship'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1496:in `each'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1496:in `validate_relationship'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:2519:in `block in finish'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:2517:in `collect' …
```

Remove a possibly undefined requirement in discovery

---

files/external_node_v2.rb
files/foreman-report_v2.rb
spec/unit/foreman_external_node_spec.rb
spec/unit/foreman_report_processor_spec.rb

Internally Puppet uses YAML.load_file to load the Hiera config (set to
/dev/null under rspec-puppet), but 4.9.0 uses Pathnames instead of
Strings causing the existing stub for "/dev/null" to fail.
Setting the value of $settings_file prior to evaluating the ENC/report
scripts is more reliable than stubbing the YAML constant.

Remove YAML.load_file stubbing, preset $settings_file

---

files/external_node_v2.rb
files/foreman-report_v2.rb

Fixes the issue of a long timeout when the server is unreachable.

Add open_timeout to the report and external node script

---

templates/_assets.conf.erb

Prevents responses with incorrect content types being served if
different, unknown types of assets are later added to the directory
(similar to #18371 where SVG was added, if 568f278 was not applied).

Restrict gzip asset serving to known extensions

---

lib/puppet/parser/functions/foreman.rb
spec/functions/foreman_spec.rb

Add parameter for timeout to foreman() parser function.  If unspecified, keep the default at 5sec.
This is useful if you are using the foreman() parser function to automatically populate templates, and you are using queries that occasionally take more than five seconds to complete.

Add param for timeout to foreman() parser function

---

manifests/cli.pp
manifests/cli/params.pp
spec/classes/foreman_cli_spec.rb
templates/hammer_etc.yml.erb

Defaults when used with main 'foreman' class to the server's CA file,
automatically ensuring Hammer CLI will trust the CA used.

Set ssl_ca_file in Hammer system-wide config file

---

.sync.yml
.travis.yml

Prevent test jobs being killed for excessive resource consumption on
Travis CI.
---
Example failure: https://api.travis-ci.org/jobs/219217285/log.txt?deansi=true (see "Killed" part way down, running 32 processes).
Corresponding modulesync change made in https://github.com/theforeman/foreman-installer-modulesync/pull/59.

Limit number of parallel_test processes

---

lib/puppet/provider/foreman_smartproxy/rest_v3.rb
lib/puppet/type/foreman_smartproxy.rb
spec/unit/foreman_smartproxy_rest_v3_spec.rb
spec/unit/foreman_smartproxy_spec.rb

Implemented on the rest_v3 provider to validate that the enabled
features found by Foreman include all of the features listed in the
'features' property on the resource.
This should detect configuration errors on the smart proxy, or missing
Foreman plugins for the registered smart proxy.

Add features property to foreman_smartproxy to check enabled features

---

lib/puppet/type/foreman_smartproxy.rb
spec/unit/foreman_smartproxy_spec.rb

Originally:
change from ["Logs", "Puppet CA", "TFTP"] to Puppet Puppet CA TFTP Logs failed
Now:
change from [Logs, Puppet CA, TFTP] to [Logs, Puppet, Puppet CA, TFTP] failed

Improve formatting of foreman_smartproxy feature lists

---

spec/classes/foreman_config_passenger_spec.rb
templates/_assets.conf.erb

The standard puppetlabs-vhost already generates a directory location for the docroot with a Require all granted. It also does the version logic in puppet code resulting in a shorter config file.
For reference the generated config file from a katello host without this change:
```
<VirtualHost *:443>
ServerName pipeline-katello-nightly-centos7.example.com
DocumentRoot "/usr/share/foreman/public"
<Directory "/usr/share/foreman/public">
Options SymLinksIfOwnerMatch
AllowOverride None
Require all granted
</Directory>
IncludeOptional "/etc/httpd/conf.d/05-foreman-ssl.d/*.conf"
ErrorLog "/var/log/httpd/foreman-ssl_error_ssl.log"
ServerSignature Off
CustomLog "/var/log/httpd/foreman-ssl_access_ssl.log" combined
ServerAlias foreman
SSLEngine on
SSLCertificateFile …
```

Remove redundant directory definition

---

lib/puppet/provider/foreman_hostgroup/rest_v2.rb
lib/puppet/type/foreman_hostgroup.rb

Added an optional parameter to toggle SSL verification, and updated to reflect Apipie's preferred oauth config.

Updated oauth syntax, support for disabling SSL Validation

---

manifests/database/postgresql.pp
manifests/init.pp
templates/database.yml.erb

To setup DB with SSL and verification use params:
db_sslmode => 'verify-full',
db_root_cert => 'ca_bundle.pem'
Default DB sslmode is 'prefer' - non-verified SSL with fallback to
non-SSL. To use SSL secured connection with CA verification sslmode
needs to be set to either 'verify-ca' or 'verify-full'. Underlying libpg
uses DB root cert stored at '~/.postgresql/root.crt' which is in case of
Foreman at '/usr/share/foreman/.postgresql/root.crt'. There is no way to
setup different path (besides using env vars). System CA trust is not
supported. The cert needs to be real file as links are not allowed too.
For more details see SSL support in libpg:
https://www.postgresql.org/docs/9.2/static/libpq-ssl.html

Fixes #20079 - SSL secured and verified Pg connection

---

manifests/config/passenger.pp
manifests/install.pp
metadata.json
spec/classes/foreman_config_passenger_spec.rb
spec/defines/foreman_config_passenger_fragment_spec.rb

Requires https://github.com/puppetlabs/puppetlabs-apache/pull/1588

Use apache mod classes

---

.fixtures.yml
manifests/plugin/discovery.pp
manifests/plugin/discovery/params.pp
metadata.json
spec/classes/plugin/discovery_spec.rb

The image downloading is tied to tftp and handled by the proxy. Since puppet-foreman_proxy is already able to download images there's no sense in duplicating the code here.
Based on https://github.com/theforeman/puppet-foreman/pull/486
I think this also needs installer migrations to remove the answers.
Closes GH-580
Closes GH-581

Remove discovery image downloading

---

manifests/init.pp
manifests/params.pp
spec/classes/foreman_config_spec.rb
templates/settings.yaml.erb

Set `unattended_url` parameter in `foreman/settings.yaml`
Enables setting of unattended_url during install with foreman-installer

Add unattended_url parameter

---

manifests/database.pp
manifests/init.pp
manifests/plugin.pp
spec/classes/foreman_database_spec.rb

Installation of the plugins can influence the API
and the apipie cache needs to be refreshed after that.

Fixes #21072 - build apipie cache after plugins

---

files/external_node_v2.rb

Change working directory to the determined home directory of
`puppetuser` before continuing to ensure we don't reside in /root or
anywhere else we don't have permissions.
Fixes #611.

Change to safe working directory in external_node_v2.rb

---

README.md
manifests/init.pp
manifests/params.pp
manifests/plugin/ansible.pp
manifests/plugin/remote_execution.pp
manifests/plugin/tasks.pp
manifests/plugin/tasks/params.pp
manifests/service.pp
manifests/service/jobs.pp
spec/classes/foreman_service_jobs.rb
spec/classes/foreman_service_spec.rb
spec/classes/plugin/remote_execution_spec.rb
spec/classes/plugin/tasks_spec.rb

The dynflow service was moved into core with 1.16. That renamed it to dynflowd and means the service should be started by default.
For compatibility parameters are provided. This means we must move the service name detection to the jobs.pp file because that's the only place we know the actual value.
This replaces https://github.com/theforeman/puppet-foreman/pull/530. It's mostly the same, but split into two commits to make reviews easier. The first is a compatible refactor where the second is just the introduction of dynflow in core.

Fixes #18757 - Handle dynflow service in foreman core

---

manifests/cli.pp
spec/classes/foreman_cli_spec.rb

Alternative to https://github.com/Katello/katello-installer/pull/574

fixes #22196 - use ssl chain for hammer if available

---

templates/database.yml.erb

These database declarations don't make sense in a production
environment which the module is focused on. If these environment
databases are desired then they can be added back properly. This
also serves to fix an odd issue in production with Dynflow.

Remove test and development database declarations

---

.sync.yml
.travis.yml

Tests are starting to fail in Travis without a clear error. We've seen
this before and reducing the concurrency has helped.

Reduce PARALLEL_TEST_PROCESSORS to 8

---

manifests/init.pp
manifests/params.pp
templates/settings.yaml.erb

@ekohl this would be really good to have in 1.18, otherwise every installer run disables telemetry configuration that users configured, cc @lzap 
note that the biggest past is indentation of comments

Fixes #23101 - add telemetry options

---

manifests/init.pp
manifests/params.pp

Hi,
This is one of a series of patches to address typos in `katello-installer --help` [#15963](http://projects.theforeman.org/issues/15963)
This diff addresses the `--foreman-custom-repo` and `--foreman-passenger-start-timeout` parameters' descriptions, changing them from:
~~~
--foreman-custom-repo         No need to change anything here by default
if set to true, no repo will be added by this module, letting you to
set it to some custom location. (current: true)
...
--foreman-passenger-start-timeout  Amount of seconds to wait for Ruby application boot. (current: 90)
~~~
To:
~~~
--foreman-custom-repo         No need to change anything here by default
if set to true, no repo will be added by this module, letting you
set it to some custom location. (current: true)
... …

Refs #15963 - katello-installer --help typos

---

manifests/plugin/wreckingball.pp
spec/classes/plugin/wreckingball_spec.rb

Adding wreckingball plugin.  RPM available [here](https://yum.theforeman.org/plugins/nightly/el7/x86_64/)

Adding wreckingball Plugin

---

manifests/config.pp
manifests/database/postgresql.pp

When a remote database is used the postgres server is not managed. This
meant that the certificate was not placed. It's moved to the config
since it's a client config that always needs to happen.

Fixes #22940 - Ensure the PG root cert is installed

---

metadata.json

Changelog: https://forge.puppet.com/puppetlabs/apt/changelog#500-2018-07-18
This is to avoid warnings with dependencies.

metadata.json: bump allowed version of puppetlabs-apt to 6.0.0

---

manifests/params.pp
manifests/repo.pp
manifests/repos.pp
manifests/repos/apt.pp
manifests/repos/yum.pp
spec/classes/foreman_repo_spec.rb
spec/defines/foreman_repos_apt_spec.rb
spec/defines/foreman_repos_spec.rb
spec/defines/foreman_repos_yum_spec.rb

* Drop use of the 'stable' repository
* Disallow releases/ as part of the repository
* Add foreman-rails repository
* Stop including foreman::params
* Remove anchor pattern
* Move to https
Will need https://github.com/theforeman/puppet-foreman/pull/659 for the acceptance tests to pass.
Note that the foreman-rails repository assumes Foreman 1.17+ so that'll become the new minimum version. I'm going to continue with removing some compatibility with older versions in follow up PRs.

Refactor repo handling

---

manifests/init.pp
manifests/params.pp
manifests/puppetmaster.pp
manifests/puppetmaster/params.pp
spec/classes/foreman_config_spec.rb
spec/classes/foreman_spec.rb
templates/settings.yaml.erb

This moves all puppetmaster defaults to its own parameters file.
Parameters that were used in both are duplicated. It also adds Puppet
types to all parameters.
This removes puppet settings from the top level. The puppet_ssldir is
now an internal detail to determine defaults. It is also no longer set
in Foreman since it's only used as a base for determining SSL paths
which we explicitly set. There is a PR open to remove this setting
altogether.

Refactor Puppet handling

---

manifests/repos/extra.pp
spec/classes/foreman_repos_extra_spec.rb

This drops support for EL6 by only having the URL for the EL6 GPG key.
It also allows setting the package state of foreman-release-scl.

Refactor extras repo handling

---

files/external_node_v2.rb

I'm not very familiar with Ruby, but I think there's some problem with the syntax.
Today I saw errors from the ENC script when the foreman server was under high load. I manually ran the script and it only gave me the following output (not sure why there weren't any stacktraces):
```
class or module required for rescue clause
```
After removing the square brackets it was able to output like this:
```
Serving cached ENC: execution expired
---
classes: {}
parameters:
```

Trying to fix rescue syntax in ENC script

---

files/external_node_v2.rb

Since https://github.com/theforeman/puppet-foreman/commit/db49c49e3b1e5a95cb5ecb34b5f1c3b494ef5938 when a node doesn't exists
Current
```bash
$ ruby node.rb fake.notexists.com
undefined local variable or method `res' for main:Object
```
Expected
```bash
$ /etc/puppet/node.rb fake.notexists.com
Error retrieving node fake.notexists.com: Net::HTTPNotFound
Check Foreman's /var/log/foreman/production.log for more information.
```

Fix wrong variable name in enc function

---

manifests/repos/apt.pp
spec/acceptance/foreman_basic_spec.rb
spec/acceptance/foreman_cli_plugins_spec.rb
spec/acceptance/foreman_journald_spec.rb
spec/acceptance/foreman_prometheus_spec.rb
spec/acceptance/foreman_statsd_spec.rb

This further unifies the tests and removes redundant workarounds. Also allows apt repo parameters to be overridden via hiera.

Clean up acceptance tests + make the apt repo parameters

---

spec/classes/foreman_spec.rb
templates/settings.yaml.erb

Since Foreman 97c34475c9e674db6443b28e03a5e4d94d585f2e (1.10+) this is actually a boolean. The string 'off' would be interpreted as the value true.

Handle websockets_encrypt as a boolean

---

manifests/init.pp
manifests/params.pp
manifests/repo.pp
spec/acceptance/foreman_cli_plugins_spec.rb
spec/acceptance/foreman_cli_spec.rb
spec/classes/foreman_install_spec.rb
spec/classes/foreman_repo_spec.rb
spec/classes/foreman_spec.rb

Because we're trying to move people away from the latest repository, we set it to configure an explicit version with a default. Because this default would need to be updated all the time, it's a bad idea.
This patch removes the $custom_repo and makes $repo undef by default. This means users get no repository by default and need to explicitly choose which repository to use.

Remove default repo management

---

manifests/init.pp
manifests/params.pp
spec/classes/foreman_spec.rb
templates/settings.yaml.erb

This is required to support: https://github.com/theforeman/foreman/pull/6467

add cors domains parameter

---

manifests/config/passenger.pp

The intention with this is allow advanced users to pass in these options via hiera. Longer term I also want to remove our use of the `custom_fragment` so that power users can use that key as well.

Expose options to the http and https vhosts

---

manifests/plugin/memcache.pp
manifests/plugin/memcache/params.pp

Using params.pp for static values needlessly complicates the class.

Simplify the memcache plugin

---

files/external_node_v2.rb

This helps with debugging and gives error output more context. For
example Foreman will not accept pushed facts for a host that is
currently being built. With this change the error message changes from
this:
During the fact upload the server responded with: 422 Unprocessable Entity. Error is ignored and the execution continues.
{"message":"ERF42-9911 [Foreman::Exception]: Host is pending for Build"}
To this, which is preferable:
app03.dev.example.com: During the fact upload the server responded with: 422 Unprocessable Entity. Error is ignored and the execution continues.
{"message":"ERF42-9911 [Foreman::Exception]: Host is pending for Build"}

Add certname to error output in external_node_v2.rb

---

files/external_node_v2.rb

Under certain conditions it can happen that Puppet Server creates a fact
yaml file for a node that contains an empty `values` hash, for example
when multiple Puppet Servers are accessed through a load balancer like
HAProxy where Puppet agent requests are distributed equally and randomly.
When trying to process such a facts file with an empty `values` hash
Foreman will reject the HTTP request with an error message like this:
During the fact upload the server responded with: 422 Unprocessable Entity. Error is ignored and the execution continues.
{"message":"ERF42-3829 [Foreman::Exception]: invalid facts, missing operating system value"}
This change adds a simple method that loads the fact yaml file and
returns true if the `values` hash is empty. Such fact yaml files are
then skipped when …

Avoid processing fact yaml files with empty 'values' hash

---

manifests/init.pp

Add Parameters for `jobs_service_*` to have a convenient Way
to get those Values through to `::foreman::service::jobs`.

Add Parameters for jobs_service

---

manifests/cli/params.pp
manifests/params.pp
manifests/plugin/ovirt_provision/params.pp
manifests/plugin/puppetdb/params.pp
manifests/plugin/tasks/params.pp

This is untested, but here so it can be tested.
cc @ehelms

Use system packages on EL8

---

spec/acceptance/foreman_journald_spec.rb

Logging to the journal is broken on Travis and EL7 but works on regular docker containers (tested with a CentOS 7 host + docker) and VMs.
This may be a bug in the logging gem but given this is not an issue in regular operation I'm not going to investigate.

Disable journalctl check on Travis

---

README.md
manifests/init.pp
manifests/params.pp
manifests/plugin/userdata.pp
spec/classes/foreman_spec.rb
spec/classes/plugin/userdata_spec.rb
templates/settings.yaml.erb

The puppetrun feature has become much less prominent and we shouldn't set this via the YAML file. This can be changed at runtime if desired or via the foreman_config_entry type.

Drop compatibility with Foreman 1.20 and older + puppetrun parameter

---

manifests/puppetmaster.pp

Going from module version 9.2.0 to 10.0.0, `foreman::puppetmaster` changed`ssl_ca`, `ssl_cert`, `ssl_key`, the values of which end up in `foreman.yaml` from being anything-you-want to being Absolutepath.
However, both `external_node_v2.rb` and `foreman-report_v2.rb` (which consume `foreman.yaml`) have conditional logic which allow those ssl values to be empty.
This change seeks to allow those parameter values to be empty, if the user wishes.

Make SSL parameters optional within foreman::puppetmaster

---

manifests/config/apache/fragment.pp

IMHO, self-explained title, isn't it? :-)
Thanks

Rely on Puppet data types to ensure variables content is valid in apache::fragment

---

README.md
lib/puppet/functions/foreman/enc.rb

This makes it possible to use Foreman as an ENC to your environment via Hiera lookups.

Implement a foreman::enc function

---

README.md
manifests/config.pp
manifests/config/apache.pp
manifests/init.pp
manifests/install.pp
manifests/params.pp
manifests/service.pp
spec/acceptance/foreman_basic_spec.rb
spec/acceptance/foreman_journald_spec.rb
spec/acceptance/foreman_prometheus_spec.rb
spec/acceptance/foreman_reverse_proxy_spec.rb
spec/acceptance/foreman_statsd_spec.rb
spec/classes/foreman_config_apache_spec.rb
spec/classes/foreman_config_ipa_spec.rb
spec/classes/foreman_service_spec.rb
spec/classes/foreman_spec.rb
spec/defines/foreman_config_apache_fragment_spec.rb
spec/spec_helper_acceptance.rb
templates/_assets.conf.erb
templates/_suburi.conf.erb
templates/settings.yaml.erb

This doesn't implement the actual reverse proxy part, but it does make passenger optional and prepares the code for it.

Rewrite to support reverse proxy

---

CHANGELOG.md
manifests/plugin/puppetdb.pp
metadata.json

dca5d41234bf54470ec96e3858caabbc4970f8f6 was intended to reduce fb5d38f8bea69ad8c6cb1300ce4d803fd89aace3 to an implementation only change but ended up being a full revert. This removes the dead setting that actively breaks installations.

Release 11.0.3 with the actual fix for #26695

---

manifests/plugin/remote_execution/cockpit.pp
spec/acceptance/foreman_rex_cockpit_spec.rb
spec/classes/plugin/remote_execution_cockpit_spec.rb

This adjusts the installer to match changes done in the REX PR[1].
[1] - https://github.com/theforeman/foreman_remote_execution/pull/441

Fixes #28200 - Change cockpit port from 9999 to 19090

---

manifests/database.pp
manifests/rake.pp
spec/classes/foreman_database_spec.rb
spec/classes/foreman_spec.rb
spec/defines/foreman_rake_spec.rb

This drops relying on a settings entry in favor of lettings Rails
tell us when there are migrations that need to be applied.

Run migrations if there are pending migrations

---

manifests/config.pp
manifests/config/apache.pp
manifests/init.pp
manifests/install.pp
manifests/params.pp
spec/classes/foreman_config_apache_spec.rb
spec/classes/foreman_config_ipa_spec.rb
spec/classes/foreman_install_spec.rb
spec/classes/foreman_spec.rb
spec/defines/foreman_config_apache_fragment_spec.rb

This was needed before we had foreman-selinux but that was introduced in Foreman 1.1. By now we can rely on only the selinux fact.

Drop the selinux parameter

---

manifests/config/apache.pp
manifests/init.pp
manifests/params.pp
spec/classes/foreman_config_apache_spec.rb
spec/classes/foreman_spec.rb
spec/defines/foreman_config_apache_fragment_spec.rb

This parameter doesn't work well since you need to configure Apache slightly different as well since out of the box it doesn't work. Users who care about this functionality can use Hiera with the `http_vhost_options` and `https_vhost_options` parameters to set the ip directly.

Drop listen_on_interface

---

.fixtures.yml
Gemfile
manifests/config.pp
manifests/dynflow/worker.pp
manifests/init.pp
manifests/install.pp
manifests/params.pp
manifests/service.pp
metadata.json
spec/acceptance/foreman_basic_spec.rb
spec/acceptance/foreman_journald_spec.rb
spec/acceptance/foreman_prometheus_spec.rb
spec/acceptance/foreman_reverse_proxy_spec.rb
spec/acceptance/foreman_rex_cockpit_spec.rb
spec/acceptance/foreman_statsd_spec.rb
spec/classes/foreman_install_spec.rb
spec/classes/foreman_service_spec.rb
spec/classes/foreman_spec.rb
spec/defines/foreman_dynflow_worker_spec.rb
spec/spec_helper_acceptance.rb
templates/dynflow_worker.yml.erb
templates/settings.yaml.erb

Install necessary sidekiq configs and dependencies.

Fixes #28067 - dynflow sidekiq services config

---

manifests/dynflow/worker.pp

If the dynflow worker service starts before the configuration file
has been deployed the worker will fail to start.

Refs #28067: Ensure dynflow worker config exists before service

---

manifests/init.pp
manifests/plugin.pp
spec/classes/foreman_spec.rb
spec/defines/foreman_plugin_spec.rb

Previously plugins were installed after the database was set up. This was usually ok because all the plugins did database migrations after being installed. However, if the migration would need any config, it could still fail.
This changes it to make sure all plugins are installed and (mostly) configured before the database is done setting up. If any plugin needs additional configuration to be present before migrating and seeding, the foreman::plugin::$myplugin class needs to additionally take care of this. Currently all existing classes do where needed.

Ensure plugins are installed before the database

---

manifests/config.pp
manifests/config/apache.pp
spec/classes/foreman_config_apache_spec.rb
spec/defines/foreman_config_apache_fragment_spec.rb

By not relying on the foreman class parameters, it becomes easier to use this class without Foreman. This can be useful when deploying it using a git checkout rather than packages. An example of that is https://github.com/theforeman/puppet-katello_devel/pull/225

Make foreman::config::apache standalone

---

manifests/init.pp
manifests/params.pp
templates/foreman.service-overrides.erb

~~I am creating this PR sooner with `DO NOT MERGE` tag to let everyone know how I am proceeding.~~
Any feedback is appreciated.
- I have so far picked only 2 parameters - `threads` and `workers`. More will be picked in the future if need be. See [sample config](https://github.com/puma/puma/blob/f22dc6172235a57c56c28e3074c76ce421170b1c/examples/config.rb) for more info.

Fixes #28955 - Added puma configuration

---

lib/puppet/functions/foreman/foreman.rb
lib/puppet/functions/foreman/smartvar.rb
manifests/config/apache.pp
manifests/repos/apt.pp

While Puppet is case insensitive on data types, Kafo does care. This matches the type to its actual definition.

Correct casing on Stdlib::HTTPUrl

---

manifests/plugin.pp
spec/defines/foreman_plugin_spec.rb

This sets the config file mode to 0640 by default because they may contain secrets such as credentials. To keep it readable for Foreman, the group is modified to $foreman::group.

Fixes #29255 - Set plugin config file mode to 0640

---

manifests/settings.pp

0e8621418b1eb3418066552945218cbad8d71f2d added this, but was a left over from an earlier iteration.

Refs #28436 - Drop unused parameter

---

manifests/config.pp
manifests/init.pp
spec/classes/foreman_spec.rb
templates/foreman.service-overrides.erb
templates/foreman.socket-overrides.erb

When using systemd socket activation, it's important that the ListenSocket matches what Puma binds on. Otherwise it may fail. This happens when is configured on [::]:3000 (dual stack) and Puma on 0.0.0.0:3000. Puma will then attempt to bind and fail because the port is already in use.
The service bind is now made explicit because systemd's ListenSocket=3000 binds on :: where Puma by default binds on 0.0.0.0:3000. This is IPv4-only, but is what was done prior to this as well. Apache is configured dual stack and the recommended deployment.
Note this depends on https://github.com/theforeman/foreman/pull/7536 and https://github.com/theforeman/foreman-packaging/pull/4894 (deb) / https://github.com/theforeman/foreman-packaging/pull/4895 (rpm).

Refs #29144 - Use systemd socket activation

---

templates/foreman.socket-overrides.erb

281f1966587ffd3d283cd8ea76371aed02f568b4 introduced the systemd socket override, but used Service instead of Socket. This causes the service to bind incorrectly.

Refs #29144 - Correct socket override

---

spec/classes/foreman_spec.rb
templates/foreman.socket-overrides.erb

281f1966587ffd3d283cd8ea76371aed02f568b4 introduced the override with the incorrect section. e642db1c690cdbc01bfc193b643bece1a5b0e91a corrected the section, but not the headers.
Currently a draft since I'm testing this.

Refs #29144 - Use the correct ListenStream

---

README.md
metadata.json
spec/spec_helper_acceptance.rb

8bc1ba3027f5b65803cda115b25e1bc6194c58e7 made the default deployment use the Puma service. That means the default requires systemd and a soft dependency no longer makes sense.
It also updates the documentation in README to match.

Make camptocamp/systemd a hard dependency

---

manifests/repos/yum.pp
spec/defines/foreman_repos_yum_spec.rb

Foreman 2.0 dropped this and needs to be removed.

Drop the separate rails repository

---

manifests/puppetmaster/params.pp

875c8377f5dfadbe1cd69635d0925765e6c2a83b started to use modern facts.  However, for these branches there is no coverage and facterdb can't find these modern facts. This causes issues in puppet-puppet which does call these branches. Ignoring lint is the quickest fix now.
Longer term these classes will be split out to its own module as theforeman/puppetserver_foreman so there can be test coverage.

Use legacy facts for puppetmaster defaults

---

manifests/params.pp
manifests/providers/params.pp
manifests/puppetmaster/params.pp
spec/support/aio.rb

This fact is a core fact that's only set on AIO installs. Setting this custom fact is also easier than the structured fact in our test suite which increases reliability of our tests.
This is finishing what https://github.com/theforeman/puppet-foreman/pull/832 intended to fix.

Switch AIO detection to use aio_agent_version fact

---

README.md
manifests/init.pp
manifests/install.pp
manifests/params.pp
spec/classes/foreman_spec.rb
templates/settings.yaml.erb

This allows to make use of redis as backend, but still defaults to file.
@timogoebel: Can you have a look as the feature was implemented by you and so you perhaps know best if the parameters make sense in this way?

Add options for rails_cache_store

---

manifests/plugin/remote_execution/cockpit.pp
spec/classes/plugin/remote_execution_cockpit_spec.rb

Previously foreman_config_entry could be executed before the database was available. This ensures the database is ready and the plugin installed before attempting to change a config setting.

Ensure Foreman is provisioned before configuring cockpit

---

.sync.yml
.travis.yml
metadata.json
spec/acceptance/foreman_cli_plugins_spec.rb
spec/classes/foreman_spec.rb
spec/classes/plugin/ovirt_provision_spec.rb
spec/classes/plugin/puppetdb_spec.rb
spec/classes/plugin/tasks_spec.rb
spec/defines/foreman_plugin_spec.rb

This is a WIP which incorporates the PRs #826 & #827 .

Fixes #29212 - support el8

---

metadata.json

6.x was breaking since it made repository management modules soft dependencies. Since we don't use these, it's not breaking here.

Allow puppet/redis 6.x

---

lib/facter/sssd.rb
manifests/config.pp
spec/classes/foreman_config_ipa_spec.rb
templates/auth_kerb.conf.erb

This prevents a collision with the ipa fact from the ipa module.
In this cherry pick the old fact is kept for compatibility.
(cherry picked from commit 631f4a6a4dbdff3580592ab28771b34d6b52bfb0)
Currently a draft since I need to test this on a real system and a PR made that easier.

Fixes #29649 - Prefix ipa and sssd facts with foreman_

---

manifests/plugin/puppetdb.pp
spec/classes/plugin/puppetdb_spec.rb

This is the same as 81a68c923a9e52a1579c599f95828042d0c95470 but for puppetdb.

Fixes #30026 - Ensure Foreman is provisioned before configuring puppetdb

---

manifests/plugin/puppetdb.pp
spec/classes/plugin/puppetdb_spec.rb

This is the same as 81a68c923a9e52a1579c599f95828042d0c95470 but for puppetdb.
(cherry picked from commit fe7b09a36752c609486f82c87e042350457aee9b)

Fixes #30026 - Ensure Foreman is provisioned before puppetdb

---

manifests/config/apache.pp
spec/classes/foreman_config_apache_spec.rb

The requests for `/icons/*` were being proxy-passed to puma, which didn't know about any icons and returned 404s.

Fixes #30456 - Fix missing icons on /pub page

---

manifests/plugin/statistics.pp
spec/classes/plugin/statistics_spec.rb

Packaging PRs (should get merged first):
* RPM: https://github.com/theforeman/foreman-packaging/pull/5389
* DEB: https://github.com/theforeman/foreman-packaging/pull/5391

Add foreman_statistics plugin

---

manifests/plugin/column_view.pp
spec/classes/plugin/column_view_spec.rb
templates/foreman_column_view.yaml.erb
types/column_view_column.pp

This PR adds support for the plugin foreman_column_view.
In my tests it worked fine, but there are some points I am not sure about:
* I used Puppet 4+ Datatypes in an excessive way for validation as some other code is already doing this but only in a much more simple way
* I fear using a hash of hashes will not work with kafo, only with Puppet
* I only added the default tests and one positive test for the configuration file, no negative one to fail if configuration is wrong
* Changes of the plugin's configuration require a restart of Foreman which I did not address
Please let me know if something requires a change in the PR.

add plugin foreman_column_view

---

manifests/config.pp
manifests/init.pp
templates/database.yml.erb

Every thread in the Puma worker can open a database connection. This means it needs to be taken into account to avoid exhasuting the pool.

Fixes #30789 - Set DB pool size dynamically

---

README.md
manifests/init.pp
manifests/params.pp

Complementary PR for https://github.com/theforeman/foreman/pull/7220 to make default new kind of logger mentioned in liked PR

fixes #29938 - change default logging layout

---

manifests/config/apache.pp
spec/classes/foreman_config_apache_spec.rb

This corrects a typo in the previous change, which unset
REMOTE_USER_USER_GROUPS instead of REMOTE_USER_GROUPS in the apache
configuration.

Refs #30535 - Correctly unset remote user groups

---

manifests/params.pp
spec/classes/foreman_spec.rb

Foreman 2.2 and later supports the newer 'multiline_request_pattern'.
This commit preserves the older 'pattern' logging_layout as the default,
in order to maintain backwards compatibility with older Foreman versions.

Use backwards compatible 'pattern' logging_layout by default

---

CHANGELOG.md
metadata.json

I bumped only the patch version despite https://github.com/theforeman/puppet-foreman/commit/cf178b3b65b7d2a7c4f7d13e24391b0ba75b35c8 being a breaking change.
I reason that this is OK because that commit does add notes to the README about overriding the new default parameter in order to maintain compatibility with Foreman older than 2.2, so this should be noted as a breaking change in the CHANGELOG and users can review that commit and find the necessary info if they are trying to use an older Foreman version.
CC: @tbrisker @ehelms @ekohl

Release 15.1.2

---

spec/classes/foreman_cli_spec.rb
templates/hammer_etc.yml.erb
templates/hammer_root.yml.erb

Considering the name of these parameters, they should be affect system-wide configuration but were set in root configuration file.
This commit fixes this unexpected behavior.

CLI: make refresh_cache and request_timeout params global

---

manifests/cli.pp
manifests/cli/params.pp
spec/classes/foreman_cli_spec.rb
templates/hammer_etc.yml.erb

This PR should be merged after #884 in order to keep changelog.
Hence the title, this PR provides a simple patch to allow user to setup a system-wide configuration file for hammer with a `use_sessions` parameter.

CLI: Allow to configure use_sessions setting

---

manifests/config.pp
manifests/config/apache.pp
manifests/init.pp
manifests/params.pp
manifests/service.pp
spec/classes/foreman_config_apache_spec.rb
spec/classes/foreman_spec.rb
spec/support/acceptance/examples.rb
templates/foreman.service-overrides.erb
templates/foreman.socket-overrides.erb

The goal of this change is to switch to using local unix sockets to bind Puma to, and also to have Apache reverse proxy to increasing the security of the communication from the reverse proxy to the socket. 
I am looking to understand if I need to enforce permissions and user-group on the socket to enhance security. There is also currently SELinux denials that are associated with this change we will need to account for. On my test system they are:
```
type=AVC msg=audit(1599591946.533:10070): avc:  denied  { connectto } for  pid=6405 comm="httpd" path="/run/puma.sock" scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:system_r:foreman_rails_t:s0 tclass=unix_stream_socket
```
SELinux policy changes needed to address -- https://github.com/theforeman/foreman-selinux/pull/113

Fixes #30803: Bind to socket for Puma and Apache

---

manifests/cli.pp

ca74301ebbd4a01efa663eea5fa3ce67914ad659 dropped support for these old Puppet versions.

Drop Puppet < 3.7.5 version check

---

manifests/config/apache.pp
spec/classes/foreman_config_apache_spec.rb

This change stems from the breakage and investigation here:
https://community.theforeman.org/t/katello-nightly-rpm-pipeline-769-failed/21468/4?u=ehelms
The shadowing of the /v2/ in Pulpcore API by Katello to provide auth causes
it to clash with the reverse proxying within the same Vhost to Foreman.
This appears to be tied to how the unix socket based reverse proxy handles things.

Set the reverse proxy host to the name of the service

---

lib/puppet/functions/foreman/foreman.rb
lib/puppet/functions/foreman/smartvar.rb
lib/puppet/parser/functions/foreman.rb
lib/puppet/parser/functions/smartvar.rb
lib/puppet/provider/foreman_resource/rest_v3.rb

Ruby 2.7 deprecated URI.escape. It also fixes 2 other small (visual) issues.
I have not tested this myself.

Fix URI.escape deprecation warning

---

lib/puppet/provider/foreman_resource/rest_v3.rb
lib/puppet/provider/foreman_smartproxy/rest_v3.rb
spec/unit/foreman_resource_rest_v3_spec.rb

Fixes #30284 - Improve smartproxy registration failure error messages

---

manifests/repos/apt.pp
spec/defines/foreman_repos_apt_spec.rb

also ensure the key is refreshed if expired

use deb gpg key from our server, not the gpg network

---

templates/lookup_identity.conf.erb

The Kerberos url is quite strict, but accepting trailing `/` is probably not bad and can avoid a lot of confusion

Fixes #32208 - accept trailing slash in Krb auth url

---

manifests/plugin/tasks.pp
spec/classes/plugin/tasks_spec.rb
templates/tasks.cron.erb

Changes the default behavior to disable task backup when enabling
the task cleanup cron job. Users who still want backups kept
on disk will need to set the parameter to true.

Fixes #32175: Allow toggling task backup when cleaning them up

---

metadata.json

The major version bump was due to dropping Puppet 5 support.

Mark compatible with puppetlabs/postgresql 7.x

---

metadata.json

67f78b9b45d1b5b8118b6575bf1902056d1978d0 changed the API and is thus a major version.

Bump major version to 17.x

---

manifests/config.pp
manifests/init.pp
spec/classes/foreman_spec.rb

This removes cleanup of email.yaml introduced in e6ead4595d3008040e56a55cc40a424ee5cb87d7. It also removes cleanup of crons introduced in 14fce641b88c189e06596262d0ce99f859336fe1. Both of them should be deployed long enough that we can assume they're gone.

Remove old email.yaml and cronjob cleanups

---

lib/puppet/functions/foreman/to_symbolized_yaml.rb
manifests/dynflow/pool.pp
manifests/dynflow/worker.pp
manifests/service.pp
spec/classes/foreman_spec.rb
spec/defines/foreman_dynflow_worker_spec.rb
spec/functions/foreman_to_symbolized_yaml_spec.rb
templates/dynflow_worker.yml.erb

The previous approach worker, but it made sidekiq default worker process all items from the default queue before moving to remote execution queue.  This change adds equal weight to the queues, making sidekiq pick jobs from both.
To achieve this a function is introduced to convert data to YAML. Foreman typically uses symbolized keys in config files. This is hard to achieve with pure Puppet so a Ruby function is used.
Replaces https://github.com/theforeman/puppet-foreman/pull/919

Fixes #31964 - Assign equal weight to sidekiq queues

---

manifests/cli/katello.pp
spec/acceptance/foreman_cli_plugins_spec.rb
spec/classes/cli_plugins_spec.rb

Adding this here will allow adding to the foreman-installer similar to all other plugin hammer packages and then allows being able to drop these requirements from the katello meta RPM (https://github.com/theforeman/foreman-packaging/blob/rpm/develop/packages/katello/katello/katello.spec#L34-L36).

Refs #32276: Add Katello hammer plugin

---

README.md
files/settings-reverse-proxy-headers.yaml
manifests/config.pp
manifests/config/apache.pp
manifests/init.pp
manifests/install.pp
manifests/params.pp
manifests/service.pp
spec/classes/foreman_config_apache_spec.rb
spec/classes/foreman_service_spec.rb
spec/classes/foreman_spec.rb
templates/foreman.service-overrides.erb
templates/foreman.socket-overrides.erb
templates/settings.yaml.erb

With Foreman 2.5, support to run with Passenger (technically mod_passenger) is dropped in favor of using Puma with a reverse proxy.
This also moves the request headers part of settings.yaml to a concat fragment to simplify some code.
It keeps in code to remove tfm-rubygem-passenger-native on EL7 which it previously didn't do, but is nice to do. It doesn't remove mod_passenger itself since that's not managed in this module.

Fixes #29780 - Drop Passenger support and target Foreman 2.4+

---

manifests/config/apache.pp
spec/classes/foreman_config_apache_spec.rb

This patchset adds a new parameter to `foreman::config::apache` called `request_headers_to_unset` containing a list of HTTP headers to be unset before proxy passing the request to the application. See the
associated issue for more information.
Please let me know if you'd rather to have the parameter exposed via `init.pp` instead.
Fixes #941

Allow customising the list of HTTP headers to unset

---

manifests/repo.pp
manifests/repos.pp
manifests/repos/yum.pp
spec/classes/foreman_repo_spec.rb
spec/defines/foreman_repos_spec.rb
spec/defines/foreman_repos_yum_spec.rb

This patch adds two parameters:
1) `foreman::repo::yum_repo_baseurl` allowing to configure the prefix of the Yum repositories URL. This permits users having mirrors of `http://yum.theforeman.org` to use this module, for instance by setting the variable to `https://enterprise/internal/mirrors/yum.theforeman.org`.
The parameter's interface is pulled up to the public class and passed down to `foreman::repos::yum` via `foreman::repos`. The name might be ambiguous as the value is ultimately used as a component of a `Yumrepo`'s `baseurl`. Happy to give it a better name.
2) `foreman::repos::yum::keypath` allowing to completely customise the location of the GPG public key used to verify the signatures of the packages in the Yum repositories configured by the module. If not set the value before …

Customisable Yum repository base URL and GPG key path

---

templates/database.yml.erb
templates/settings.yaml.erb

This brings the two files in sync with how they include the
_header.erb subtemplate.
Now, you might look at this and think, "what a silly commit."  Possibly, but, I've been having this issue where `database.yml` will have two _header.erb instances if `puppet agent` runs things, and only one _header.erb if I do a `puppet apply`.  `settings.yaml` doesn't do this, it always has one copy of the header.  Of course, if `database.yml` changes, that triggers all sorts of rakes and refreshes, which makes it so I can't tell if the prospective changes I'm testing with 'agent' are noisy or fine.
I then added the triple dash to open the yaml file, since it wasn't there on database.yml.
And I also added a `-` to remove a newline in `settings.yaml`, because otherwise it has a double newline after its …

Make database.yml and settings.yaml have consistent headers

---

manifests/config/apache.pp
spec/classes/foreman_config_apache_spec.rb

When the Apache instance configured by this module is not dealing with user requests directly because there's another proxy in front, it's undesirable that the "local" Apache resets headers like X-Forwarded-Host. When it does, it could happen that links created using Rails _url helpers do not contain the Host initially sent by the client leading to broken links (as they point to backend nodes not reachable by the user).
This patch makes this setting customisable by the administrator by exposing it a parameter.
Fixes #952

Allow customising ProxyAddHeaders

---

manifests/init.pp
manifests/params.pp
spec/classes/foreman_spec.rb
templates/settings.yaml.erb

As part of CVE-2021-3584 the option email_sendmail_location was limited to just 4 choices. This allows admins to set it via settings.yaml. The idea is that if you can edit settings.yaml, you're already compromised while UI could be less protected.
When a setting is present in settings.yaml, the option becomes read-only in the UI.
If the options are not set, they don't show up in settings.yaml.

Fixes #32827 - Add sendmail config options

---

manifests/config.pp
manifests/params.pp
spec/acceptance/hieradata/common.yaml
spec/classes/foreman_spec.rb

Looking for feedback here as I don't know what the exact correct answer is to prevent the following error when setting `puppet::server` to false:
```
2021-04-15 20:08:58 [ERROR ] [configure] Could not set groups on user[foreman]: Execution of '/sbin/usermod -G puppet foreman' returned 6: usermod: group 'puppet' does not exist
2021-04-15 20:08:58 [ERROR ] [configure] /Stage[main]/Foreman::Config/User[foreman]/groups: change from  to 'puppet' failed: Could not set groups on user[foreman]: Execution of '/sbin/usermod -G puppet foreman' returned 6: usermod: group 'puppet' does not exist
```
It feels like a user of the module should not have to explicitly configure the `user_groups` if they are setting `puppet::server` to false and that the module should adjust appropriately.
The …

Refs #32885: Add puppet user to user_groups only if server or client certificate contains puppet path

---

lib/puppet/type/foreman_smartproxy.rb
manifests/providers.pp
spec/classes/foreman_providers_spec.rb

With this it's sufficient to include foreman::providers where prior to this the caller was responsible for ensuring the correct dependency.

Autorequire provider in smartproxy type

---

manifests/config.pp
manifests/init.pp
manifests/params.pp
spec/classes/foreman_config_ipa_spec.rb
templates/auth_gssapi.conf.erb

Apache is packaged in different locations between Red Hat and Debian. The user differs (apache vs www-data) and conf dir (/etc/httpd vs /etc/apache2). This changes the code to use variables already defined on the apache module to avoid duplicating this logic.

Fixes #32947 - Use Apache module variables

---

manifests/init.pp
manifests/params.pp
manifests/settings.pp
spec/classes/foreman_spec.rb

Simple patch which adds parameters to the main class to configure the two parameters email_reply_address and email_subject_prefix, which were missing on the interface. I needed to set at least the reply_address as our mail server denied the mails with the default domain ending. I appended the existing tests used for the settings already on the interface.

Configurable: email_reply_address, email_subject_prefix

---

lib/facter/sssd.rb
lib/facter/util/sssd.rb
manifests/config.pp
spec/classes/foreman_config_ipa_spec.rb

ipa-getkeytab can figure out the default server on its own[1]. There is no need to specify it and can even break things. For example, DNS can be used to detect servers. Then the fact is empty and it fails while the command would actually pass.
The fact is simplified since it's a major version bump anyway and nothing else should use our foreman_ipa fact.
[1] https://github.com/theforeman/puppet-foreman/pull/880#issuecomment-683902223
Replaces https://github.com/theforeman/puppet-foreman/pull/880

Fixes #29649 - Drop default_server argument in IPA

---

manifests/config.pp
manifests/params.pp
spec/classes/foreman_spec.rb

In dcb8a702c68dda775e4c089433039b052e2d86d7 the shell was changed from /sbin/nologin to /bin/false since on Debian it is /usr/sbin/nologin.
Technically we can now always use /usr/sbin/nologin since on EL7 /sbin is a symlink to /usr/sbin, but that doesn't match packaging. Aligning this to packaging means there's one step that no longer needs to happen during installation.
The parameter is not exposed in init.pp since most users won't care about this (in the past 6 years no PR has been submitted to do so).
This matches what the RPM and Debian packages already do so it should have no effect in reality, but it does align the two.

Match Foreman user to what packaging creates

---

manifests/config.pp

Currently we're using your modul to install and configure Foreman. 
We want to install Foreman in its own filesystem, but the file ressource for $foreman::app_root makes it hard to implement this in puppet - it will always result in duplicate ressource.  Furthermore i'm not sure, if this ressource is necessary or placed in the right class (ordering, first install the package and then create the directory?!).
Testing if this directory is already defined gives other the chance to do some stuff, e.g. creating a filesystem before installing foreman :)

Handle duplicate file declaration for foreman::app_root

---

spec/classes/foreman_cli_spec.rb

This can be tested with native methods. The only difference is that now we need to test for comments and whitespace too, but this is not a bad thing.

Replace use of verify_exact_contents

---

manifests/config.pp
manifests/init.pp
manifests/params.pp
spec/classes/foreman_spec.rb
templates/foreman.service-overrides.erb

The Puma documentation recommends for MRI based installations to
start with number of CPUs times 1.5 and defaults to 5 on Ruby MRI.
The previous maximum threads of 16 was based on an incorrect reading
of the Puma documentation and is only the default on non-MRI Ruby.
I am recommending we make these default changes (and consider resetting existing installations that match the old defaults by way of an installer migration) based upon some of the following info:
* Puma recommendations for MRI: https://github.com/puma/puma/blob/master/docs/deployment.md#mri
* Puma worker utilization: https://github.com/puma/puma/blob/master/docs/deployment.md#worker-utilization
* Gitlab's thread guidance: https://docs.gitlab.com/ee/install/requirements.html#puma-threads

Fixes #33277: Change Puma default workers to 1.5 * CPU, max threads to 5

---

manifests/config.pp
spec/classes/foreman_spec.rb

sometimes dynflow workers are started before redis, resulting in ugly
errors in the logs until redis is available

Fixes #33511 - configure redis before dynflow workers

---

manifests/install.pp
spec/classes/foreman_spec.rb

As there are packages installed by the module that escape from the version pin that can be set via `foreman::version`, the following situation might occur:
(Assuming `foreman::version` set to `2.4.0-1` and that `2.4.1-1` is the latest version available in the configured repositories)
* Puppet run `n`
* Puppet installs `foreman-postgresql-2.4.0-1`.
* Puppet installs `foreman-service` latest (due to `ensure => installed`)
* DNF installs `foreman-service-2.4.1-1`
* This triggers the update of `foreman` to `foreman-2.4.1-1` to match `foreman-service`'s requirements.
* This triggers the update of `foreman-postgresql` to `2.4.1-1` to match `foreman-postgresql`'s dependency on `foreman`.
* The Puppet run ends leaving the system in an undesired state.
* Puppet run `n+1`:
* Puppet downgrades …

Apply version restrictions to all packages

---

manifests/config.pp
manifests/config/apache.pp
manifests/init.pp
manifests/params.pp
spec/classes/foreman_config_apache_spec.rb
spec/classes/foreman_spec.rb

This parameter could be used to configure a directory with CA certificates to be trusted. This parameter is generally not used and `$server_ssl_cert` is preferred.
The parameter was introduced in 08911c3a6c776462fcc1aa99103fe588b8feb365 to override the default in puppetlabs-apache. Prior to version 2.1.0 it used to default to the system store, which created a security problem.  In puppetlabs-apache 2.1.0 [the default was changed to undef](https://github.com/puppetlabs/puppetlabs-apache/commit/7bb35c2293c12ce52329a4391fe1f20389efef06). Since this module depends on >= 5.5.0, it's safe to assume we don't need it.
It can still be set via Hiera:
```yaml
foreman::config::apache::https_vhost_options:
ssl_certs_dir: /path/to/certs/dir
```

Drop server_ssl_certs_dir parameter

---

metadata.json

Foreman 2.5 introduced support for Ubuntu Focal. This should be reflected here.

Add Ubuntu 20.04 support & drop Ubuntu 18.04

---

.fixtures.yml

This removes the unneeded version contraint for Puppet >= 6. Metadata
sets the minimal puppet version to 6.15.

Cleanup .fixtures.yml

---

lib/puppet/provider/foreman_smartproxy_host/rest_v3.rb
spec/unit/foreman_smartproxy_host_rest_v3_spec.rb

@adamruzicka Could you take a look at this
I identified this over here -- https://github.com/theforeman/foreman-operations-collection/runs/4395871312?check_suite_focus=true#step:6:939

Fix lack of idempotency in foreman_smartproxy_host provider

---

manifests/database.pp

With Puppet you can write:
```puppet
Class['A'] ~> Class['B'] ~> Class['C']
```
This implies `Class['A'] ~> Class['C']` and rspec-puppet actually will tell you that chaining is there, but it doesn't actually happen. This was reported in https://github.com/rodjek/rspec-puppet/pull/821.
In this particular case it means that if DB seeding doesn't happen then the apipie caches indexes aren't refreshed. By chaining it to db:migrate there's a much bigger chance it actually happens.
Normally apipie:cache:index needs to run after a package is updated so ideally this would actually be done in packaging, but this is the workaround we've been using for a long time.

Fixes #34161 - Run apipie:cache:index after db:migrate

---

manifests/init.pp

Due to a [bug in Kafo](https://projects.theforeman.org/issues/21398), the Stdlib::IP::Address data type can't be used. This [broke the nightly build](https://community.theforeman.org/t/foreman-installer-develop-package-release-1015-failed/26627/3).
By reducing the type to simple `String[1]` and asserting in the body the same guarantee is given, but with a worse UX if it does fail.
Currently our pipelines are broken due to Psych 4 being pulled in by rdoc 6.4 which is incompatible with Puppet.

Refs #34089 - Work around Kafo type parsing bug

---

manifests/repo.pp
spec/classes/foreman_repo_spec.rb

This is a rebase of https://github.com/theforeman/puppet-foreman/pull/1012

foreman::repo: use the package resource 'ensure' parameter to specify the desired ruby stream

---

README.md
lib/puppet/provider/foreman_hostgroup/rest_v3.rb
lib/puppet/type/foreman_host.rb
lib/puppet/type/foreman_hostgroup.rb
lib/puppet/type/foreman_instance_host.rb
lib/puppet/type/foreman_smartproxy.rb
lib/puppet/type/foreman_smartproxy_host.rb
lib/puppet_x/foreman/common.rb
spec/acceptance/foreman_hostgroups_spec.rb
spec/types/foreman_hostgroup_spec.rb
spec/unit/foreman_hostgroup_rest_v3_spec.rb

Limitations:
* Very few properties supported.
Features:
* Supports creating and deleting hostgroups with or without parents
* Autorequires parent hostgroups
* Supports hostgroup (or parents) names with slashes in them [1]
* Supports organizations/locations
* Updates to properties are combined in `flush` method.
TODO:
[1]
The following works...
```puppet
foreman_hostgroup { 'weird 1':
name        => 'weir/d',
description => 'A hostgroup with a slash in',
}
foreman_hostgroup { 'weird2':
parent_hostgroup      => 'weir/d',
parent_hostgroup_name => 'weir/d',
description           => 'A child of a weird hostgroup',
}
```

Add basic `foreman_hostgroup` type

---

manifests/database.pp

This is similar to a293e0084d3c2d62c12ccc6a13338b5db01fe8cf and the problem is that a transitive notify doesn't always happen. However, if a db:migrate happens a db:seed should always happen. So his may be a redundant specification, but it's better to be explicit than relying on implicit behavior.

Fixes #34308 - Explicitly notify db:seed from db:migrate

---

CHANGELOG.md
metadata.json

This release is intended to go in Foreman 3.1.1. It's quite large for a .z release but I don't see any breaking changes so I'd feel comfortable with it.

Release 19.1.0

---

manifests/config.pp
manifests/config/apache.pp
manifests/settings_fragment.pp
spec/defines/foreman_settings_fragment_spec.rb

This provides a stable API to provide fragments to settings.yaml. This means we don't need to create parameters for every single setting.

Introduce foreman::settings_fragment

---

manifests/repos/apt.pp
spec/defines/foreman_repos_apt_spec.rb

The old key was created in 2016 and the new one in 2021. Since 2022-03-14 the old key expired and is no longer used.

Use the new GPG key for Debian packages

---

metadata.json

using plaintext git URLs isn't supported by GitHub anymore. People might
parse the metadata.json to get the git URL which will then fail.

metadata.json: Use https URL to git repo

---

manifests/database.pp
manifests/init.pp
manifests/plugin.pp
spec/classes/foreman_database_spec.rb
spec/classes/foreman_spec.rb

Apipie cache has been explicitly disabled in Foreman so don't waste
time generating an index.

Fixes #34640 - Drop apipie:cache:index

---

manifests/service.pp
spec/acceptance/foreman_service_spec.rb
spec/classes/foreman_service_spec.rb

we need to restart foreman.service *before* a (possible) restart of
foreman.socket, as the later *also* does restart foreman.service which
leads to foreman.socket being *started* instead of *restarted*
/Service[foreman.socket]: Starting to evaluate the resource (2265 of 2522)
Executing: '/bin/systemctl is-active -- foreman.socket'
Executing: '/bin/systemctl restart -- foreman.socket'
/Service[foreman]: Starting to evaluate the resource (2266 of 2522)
Executing: '/bin/systemctl is-active -- foreman'
Executing: '/bin/systemctl show --property=NeedDaemonReload -- foreman'
Executing: '/bin/systemctl daemon-reload'
Executing: '/bin/systemctl unmask -- foreman'
Executing: '/bin/systemctl start -- foreman'
Executing: '/bin/systemctl is-enabled -- foreman' …

Fixes #34824 - properly restart foreman when puma config changed

---

lib/puppet/provider/foreman_resource/rest_v3.rb
spec/unit/foreman_resource_rest_v3_spec.rb

Setting the base_url param on all foreman_* resource declarations isn't
very DRY (resource defaults are another option).  Deriving this value
from /etc/foreman-proxy/settings.yml is consistent with looking up
tls/oauth data in /etc/foreman/settings.yaml.

derive base_url from foreman-proxy/settings.yml by default

---

.sync.yml
spec/spec_helper.rb
templates/foreman.socket-overrides.erb

Upstream foreman.socket uses NoDelay=true with a TCP socket, but on UNIX
sockets this just generates a useless warning. Explicitly setting it
back to false in our override fixes the issue.

Fixes #35089 - set NoDelay=false when deploying a UNIX socket

---

manifests/plugin/remote_execution/cockpit.pp
spec/classes/plugin/remote_execution_cockpit_spec.rb
templates/remote_execution_cockpit_session.yml.erb

This function can output the same thing and removes the need for a template.
Currently untested but unit tests should cover this.

Replace template with to_symbolized_yaml function

---

manifests/config/apache.pp

Since puppetlabs/puppetlabs-apache@f41251e String values are no longer allowed for this parameter

Use Integer type for vhost ssl_verify_depth

---

metadata.json

5a3ddb0add304fa48ab03aaf36508a4911848dd2 already made it compatible. Now that it's officially out it should be marked as compatible.

Allow puppetlabs/apache 8.x

---

manifests/config/apache.pp
spec/classes/foreman_config_apache_spec.rb

This is the default path that Apache uses for the server-status. Right now it's not used by Foreman. If mod_status is present, this allows monitoring of Apache.

Fixes #35356 - Don't proxy /server-status

---

manifests/config/apache.pp
spec/classes/foreman_config_apache_spec.rb

Includes #1078, because I am lazy and don't want to rebase again.

Drop /pulp2 and /streamer from no_proxy_uris

---

manifests/rake.pp

This makes master pass again. Also removes a workaround that's no longer needed.

Puppet-lint fixes

---

lib/puppet/functions/foreman/foreman.rb

CGI.escape can only deal with strings and the function accepts per_page as an integer.

Convert per_page in foreman::foreman to string

---

metadata.json

This is required for SSO to work correctly with Keycloak.

Fixes #35524 - Require puppetlabs-apache 8.x

---

spec/acceptance/foreman_journald_spec.rb

In Foreman 3.5 the Dynflow startup procedure was changed. It now signals it's ready before it's actually started up. This is because it can run into passive mode, in case there are multiple orchestrators. This changes the expectation so it's reliably testing it.

Refs #35414 - Expect a different message in journal

---

manifests/config.pp
spec/acceptance/foreman_basic_spec.rb
spec/classes/foreman_spec.rb
templates/settings.yaml.erb

This automatically manages Redis when the cache store type is set to Redis, but no URLs have been provided. It's assumed that when a URL is provided that the service is managed in another way.
This ignores the edge case where the user wants to run it on localhost, but with a different database than 0.
Currently a draft since it doesn't have tests and I haven't verified it yet. The end goal of this is that we can set up Redis caching by default. File based caching is just not the right fit for large deployments, even if it's stored in tmpfs.

Fixes #36037 - Manage Redis service for Redis cache

---

metadata.json

https://github.com/puppetlabs/puppetlabs-apache/commit/6130c0e9ddb8bc0d50d69d49b545f34c2762430a rev'ed that module to 9.0.0, making metadata.json here be behind the times.
I don't know if there's knock-on effects / things you need to do before landing this, but, wanted to at least note the disconnect.

Bump puppetlabs/apache to < 10.0.0

---

manifests/plugin/proxmox.pp
spec/classes/plugin/proxmox_spec.rb

In foreman-documentation, we're in the process of adding documentation on how to use Proxmox as compute resource provider in Foreman. See https://github.com/theforeman/foreman-documentation/pull/2142#issuecomment-1505340750

Refs #36319 - Add fog_proxmox plugin support

---

manifests/plugin/digitalocean.pp
manifests/plugin/docker.pp
manifests/plugin/spacewalk.pp
spec/classes/plugin/digitalocean_spec.rb
spec/classes/plugin/docker_spec.rb
spec/classes/plugin/spacewalk_spec.rb

Both have been archived. Docker is already removed from packaging, Spacewalk is still there but should also be dropped.

Remove Docker, Spacewalk & DigitalOcean plugins

---

metadata.json

the breaking changes are dropping Debian 9 and Puppet 6, which is fine for us

allow puppet/redis 9.x

---

manifests/config.pp
manifests/init.pp
spec/classes/foreman_spec.rb
templates/settings.yaml.erb

When the file logger is used the multiline_request_pattern layout should be used by default, but with journald the request ID is already stored as structured data with the log, so the pattern layout is better. The the best layout for the logging type is now used if no layout is specified.

Fixes #36582 - Detect logging layout based on type

---

README.md
manifests/config.pp
spec/classes/foreman_spec.rb

On a typical Katello installation Dynflow uses DB 6 and Pulp uses DB 8. Other applications may also use the default DB. Using DB 4 should not conflict.
@evgeni this is something you raised yesterday.
This probably deserves a release note. We should also consider cleaning up the old DB. By default Redis is configured for persistence so it should remain even after a restart. According to the internet using `redis-cli -n 0 flushdb` should do that. I don't think it's something we want to do automatically. If users don't do this, they will expire eventually anyway and the cache is not that large.

Fixes #36645 - Change the default Redis cache DB to 4

---

spec/classes/foreman_spec.rb
templates/settings.yaml.erb

the `email_` prefix is wrong, the settings have no such prefix
Fixes: 6c902a4f1f484137ebccafe4d3390881fd0b3d61

correct sendmail configuration

---

spec/classes/foreman_spec.rb

The puppetlabs/postgresql module has been refactored for multi-instance support. This means the internal implementation detail was changed.

Fix postgresql service name in test expectations

---

manifests/plugin.pp
manifests/plugin/remote_execution/cockpit.pp
spec/classes/plugin/remote_execution_cockpit_spec.rb
spec/defines/foreman_plugin_spec.rb

This doesn't deal with the database, but cockpit is a special plugin in that it's a subpackage of the regular Remote Execution plugin.
By default it uses `undef` so you can still set the version globally as well.
While this plugin doesn't use a config file via `foreman::plugin`, I looked at the source and decided to fix that too.

Fixes #36090 - Support REX cockpit removal

---

manifests/providers.pp
metadata.json

The `ensure_packages()` function is deprecated. The successor is `stdlib::ensure_packages().

require puppetlabs/stdlib 9.x 

---

manifests/config.pp
spec/classes/foreman_spec.rb
templates/_header.erb
templates/database.yml.epp
templates/settings.yaml.erb

Rather than including this directly via ERB (which raises a deprecation warning), this uses more native methods.

Include settings header via concat

---

lib/puppet/functions/foreman/foreman.rb
metadata.json
spec/functions/foreman_foreman_spec.rb

This PR should be split up for a better changelog:
* https://github.com/theforeman/puppet-foreman/pull/1140
* https://github.com/theforeman/puppet-foreman/pull/1141
* https://github.com/theforeman/puppet-foreman/pull/1142

Add Puppet 8 support

---

manifests/repo.pp

We don't intend to use modularity on the initial release, so scope this to only EL8.

Only install dnf module on EL8

---

metadata.json

The breaking change was the removal of Debian 10 support, which doesn't affect this module.

Mark compatible with puppet/redis 10.x

---

manifests/config/apache.pp
spec/classes/foreman_config_apache_spec.rb

See https://community.theforeman.org/t/user-avatar-support-in-the-foreman-keep-it-or-drop-it/32271

Fixes #37211 - Add ProxyPass for /images to support avatars

---

metadata.json

systemd has moved forward, allow this module to follow along.

Allow puppet/systemd 7.x

---

manifests/config.pp
manifests/init.pp
spec/classes/foreman_spec.rb

According to an investigation described in https://community.theforeman.org/t/rails-connection-pool-size-optimizations/36675 foreman process spawns 4 additional threads that consume DB connection during the startup. Hence the amount of acctive DB connections should be the amount of puma threads + 4 additional threads.

Fixes #33974 - Change the pool size to threads + 4

---

manifests/rake.pp
spec/defines/foreman_rake_spec.rb

this is useful when debugging which migrations ran and how long they
took

always log foreman-rake output

---

manifests/config/apache.pp
manifests/plugin/remote_execution/cockpit.pp
spec/classes/foreman_config_apache_spec.rb
spec/classes/plugin/remote_execution_cockpit_spec.rb
templates/cockpit-apache-ssl-rewrite.conf.erb
templates/cockpit-apache-ssl.conf.erb

RewriteRules need special handling of some characters (esp "?"), which
differs based on Apache version. Instead of going down that way, we can
switch to using ProxyPass as proxying is the only thing we really need
here, at least for HTTP.
For WebSockets, we need to allow protocol upgrades, which modern
(2.4.47+) Apache can do itself via "ProxyPass … upgrade=websocket".
For older Apache (esp on EL8 and Ubuntu 20.04), we keep the RewriteRules
in place. To be removed when we drop support for those targets.
Co-Authored-By: Adam Ruzicka <aruzicka@redhat.com>

Fixes #37761 - use ProxyPass and upgrade=websocket where possible

---

manifests/plugin.pp
manifests/plugin/remote_execution/cockpit.pp
spec/classes/plugin/remote_execution_cockpit_spec.rb
spec/defines/foreman_plugin_spec.rb

the package resource type supports the following values for the `ensure` parameter:
*    present
*    absent
*    purged
*    disabled
*    installed
*    latest
*    /./
this change adds support for *purged* as it has the same effect in the context of this module.

add support for plugin `ensure` stage *purged*

---

templates/database.yml.epp

database passwords can contain special characters, especially " and '
so we can't just print the value of the field enclosed by double quotes
as that would break whenever the user uses a literal " in their password
using to_ruby here and not to_yaml, as the former gives us correct escaping
without the whole `---` and `\n` enclosing that to_yaml forces.
using to_yaml would require to pass *the whole* config hash to it

properly escape quotes in passwords by calling to_ruby

---

manifests/config.pp

Users can easily run out of PostgreSQL connections on large deployments.  This provides a ceiling to the automatically calculated Puma workers because it's unclear if that really provides performance benefits while it can break deployments.
Not noticable here, but foreman-installer defaults to max 500 PostgreSQL connections and has tuning options that to increase it to 1000.
Ideally it would be smarter, but it's really hard to account for all possible conditions.

Fixes #38085 - Cap the number of Puma workers at 100

---

spec/acceptance/foreman_rex_cockpit_spec.rb
spec/support/acceptance/purge.rb

1. the family is called `redhat`, not `centos`
2. to apply a manifest, you need to define `manifest` not `pp`

fix foreman_rex_cockpit acceptance test

---

manifests/cli/bootdisk.pp
spec/acceptance/foreman_cli_plugins_spec.rb
spec/classes/cli_plugins_spec.rb

Based on eadb4edb11ee56e7edcfe4c8e61cc93cfc121af2
https://projects.theforeman.org/issues/38228
Tested locally by cherry-picking on Foreman 3.11; compared the stdout of foreman-installer, dnf, and hammer which all looked sane to me.
Refs https://github.com/theforeman/foreman-installer/pull/1009

Fixes #38228 - Add Hammer CLI for foreman_bootdisk

---

manifests/config/apache.pp
spec/classes/foreman_config_apache_spec.rb

underscores are not allowed in HTTP headers and some backends reject
headers using underscores before converting incoming dashes to
underscores to pass to the app

use dashes, not underscores when settings HTTP headers

---

manifests/database/postgresql.pp
manifests/database/postgresql/encoding.pp
spec/classes/foreman_database_spec.rb

By calling `stdlib::ensure_packages()` in the class itself the resource gets tied to the class. If other packages also depend on the resource, you can get dependency cycles.
In particular, candlepin also does this and that causes a dependency cycle.
By using a class that is included the resource "floats" in the catalog. We then only ensure the package is installed somewhere before we create the database.
Link: https://github.com/theforeman/puppet-candlepin/commit/ca771455713546b6eb216116d546526097d3e71c
Fixes: 768a54ec814d ("Ensure glibc-langpack-en is always installed on EL")

Avoid dependency cycles with glibc-langpack-en

---

manifests/config.pp
spec/classes/foreman_spec.rb

In some cases a database migration can reach out to Redis. It should fail gracefully if Redis isn't available, but it's better to ensure it is available.

Fixes #38517 - Ensure Redis is running before db:migrate

---

.fixtures.yml

Since we pull the main branch for testing, and it was updated to drop Puppet 7 support Debian and Ubuntu testing fails:
https://github.com/puppetlabs/puppetlabs-apt/commit/3f9afe6a4840a5804a740d924f6fde0b277db8e0

Pin puppet-apt since it dropped Puppet 7

---

metadata.json

https://forge.puppet.com/modules/puppetlabs/apache 13.0.0 was released, but our modules only allow "< 13"
Updating upper bound to "< 14" to fix this issue

Allow puppetlabs/apache 13.x
